INSERT INTO "producto" ("nombre", "categoria", "subcategoria", "subsubcategoria", "marca", "peso", "descripcion",
                        "precio", "imgpath1", "imgpath2", "imgpath3")
VALUES ('Manzana', 'Frutas', 'Frutas Frescas', NULL, 'Marca A', '1 kg', 'Manzana roja fresca', 2.50, 'Manzana_1.png',
        'Manzana_2.png', 'Manzana_3.png'),
       ('Banana', 'Frutas', 'Frutas Frescas', NULL, 'Marca B', '1 kg', 'Banana amarilla madura', 1.80, 'Banana_1.png',
        'Banana_2.png', 'Banana_3.png'),
       ('Pera', 'Frutas', 'Frutas Frescas', NULL, 'Marca A', '1 kg', 'Pera jugosa y dulce', 2.75, 'Pera_1.png',
        'Pera_2.png', 'Pera_3.png'),
       ('Leche', 'Lacteos', 'Leche', 'Entera', 'Marca C', '1 litro', 'Leche entera pasteurizada', 1.20, 'Leche_1.png',
        'Leche_2.png', 'Leche_3.png'),
       ('Yogurt', 'Lacteos', 'Yogurt', 'Natural', 'Marca D', '500 g', 'Yogurt natural sin azucar', 1.50, 'Yogurt_1.png',
        'Yogurt_2.png', 'Yogurt_3.png'),
       ('Queso', 'Lacteos', 'Quesos', 'Fresco', 'Marca E', '250 g', 'Queso fresco de cabra', 3.40, 'Queso_1.png',
        'Queso_2.png', 'Queso_3.png'),
       ('Pan', 'Panaderia', 'Panes', 'Integral', 'Marca F', '500 g', 'Pan integral con semillas', 2.20, 'Pan_1.png',
        'Pan_2.png', 'Pan_3.png'),
       ('Croissant', 'Panaderia', 'Pasteles', 'Dulce', 'Marca G', '100 g', 'Croissant de mantequilla', 1.00,
        'Croissant_1.png', 'Croissant_2.png', 'Croissant_3.png'),
       ('Bagel', 'Panaderia', 'Panes', 'Clasico', 'Marca H', '100 g', 'Bagel clasico', 0.90, 'Bagel_1.png',
        'Bagel_2.png', 'Bagel_3.png'),
       ('Arroz', 'Cereales', 'Arroz', 'Integral', 'Marca I', '1 kg', 'Arroz integral organico', 1.80, 'Arroz_1.png',
        'Arroz_2.png', 'Arroz_3.png'),
       ('Harina', 'Cereales', 'Harinas', 'Trigo', 'Marca J', '1 kg', 'Harina de trigo todo uso', 1.20, 'Harina_1.png',
        'Harina_2.png', 'Harina_3.png'),
       ('Pasta', 'Cereales', 'Pasta', 'Spaghetti', 'Marca K', '500 g', 'Spaghetti de trigo duro', 1.00, 'Pasta_1.png',
        'Pasta_2.png', 'Pasta_3.png'),
       ('Aceite de Oliva', 'Aceites', 'Aceites Vegetales', NULL, 'Marca L', '500 ml', 'Aceite de oliva extra virgen',
        5.00, 'Aceite de Oliva_1.png', 'Aceite de Oliva_2.png', 'Aceite de Oliva_3.png'),
       ('Mantequilla', 'Aceites', 'Mantequillas', NULL, 'Marca M', '200 g', 'Mantequilla sin sal', 2.50,
        'Mantequilla_1.png', 'Mantequilla_2.png', 'Mantequilla_3.png'),
       ('Miel', 'Endulzantes', 'Mieles', NULL, 'Marca N', '250 g', 'Miel de abeja pura', 3.75, 'Miel_1.png',
        'Miel_2.png', 'Miel_3.png'),
       ('Azucar', 'Endulzantes', 'Azucar', 'Blanca', 'Marca O', '1 kg', 'Azucar blanca refinada', 1.10, 'Azucar_1.png',
        'Azucar_2.png', 'Azucar_3.png'),
       ('Sal', 'Condimentos', 'Sales', 'Marina', 'Marca P', '500 g', 'Sal marina fina', 0.80, 'Sal_1.png', 'Sal_2.png',
        'Sal_3.png'),
       ('Pimienta', 'Condimentos', 'Especias', 'Negra', 'Marca Q', '50 g', 'Pimienta negra molida', 1.50,
        'Pimienta_1.png', 'Pimienta_2.png', 'Pimienta_3.png'),
       ('Canela', 'Condimentos', 'Especias', 'Molida', 'Marca R', '50 g', 'Canela molida', 1.20, 'Canela_1.png',
        'Canela_2.png', 'Canela_3.png'),
       ('Tomate', 'Verduras', 'Vegetales Frescos', NULL, 'Marca S', '1 kg', 'Tomate rojo maduro', 2.30, 'Tomate_1.png',
        'Tomate_2.png', 'Tomate_3.png'),
       ('Zanahoria', 'Verduras', 'Vegetales Frescos', NULL, 'Marca T', '1 kg', 'Zanahoria fresca', 1.50,
        'Zanahoria_1.png', 'Zanahoria_2.png', 'Zanahoria_3.png'),
       ('Lechuga', 'Verduras', 'Vegetales Frescos', NULL, 'Marca U', '1 pieza', 'Lechuga romana', 1.20, 'Lechuga_1.png',
        'Lechuga_2.png', 'Lechuga_3.png'),
       ('Papas', 'Verduras', 'Tuberculos', NULL, 'Marca V', '1 kg', 'Papas blancas', 1.80, 'Papas_1.png', 'Papas_2.png',
        'Papas_3.png'),
       ('Cebolla', 'Verduras', 'Vegetales Frescos', NULL, 'Marca W', '1 kg', 'Cebolla amarilla', 1.50, 'Cebolla_1.png',
        'Cebolla_2.png', 'Cebolla_3.png'),
       ('Ajo', 'Verduras', 'Vegetales Frescos', NULL, 'Marca X', '200 g', 'Ajo blanco', 2.00, 'Ajo_1.png', 'Ajo_2.png',
        'Ajo_3.png'),
       ('Pollo', 'Carnes', 'Aves', NULL, 'Marca Y', '1 kg', 'Pechuga de pollo fresca', 5.00, 'Pollo_1.png',
        'Pollo_2.png', 'Pollo_3.png'),
       ('Res', 'Carnes', 'Carnes Rojas', NULL, 'Marca Z', '1 kg', 'Carne de res para asar', 7.50, 'Res_1.png',
        'Res_2.png', 'Res_3.png'),
       ('Pescado', 'Pescados y Mariscos', 'Pescados', NULL, 'Marca AA', '1 kg', 'Filete de salmon', 10.00,
        'Pescado_1.png', 'Pescado_2.png', 'Pescado_3.png'),
       ('Camaron', 'Pescados y Mariscos', 'Mariscos', NULL, 'Marca BB', '500 g', 'Camarones grandes', 8.00,
        'Camaron_1.png', 'Camaron_2.png', 'Camaron_3.png'),
       ('Huevos', 'Huevos', 'Huevos de Gallina', NULL, 'Marca CC', '12 unidades', 'Huevos frescos', 2.40,
        'Huevos_1.png', 'Huevos_2.png', 'Huevos_3.png'),
       ('Tofu', 'Proteinas Vegetales', 'Soja', NULL, 'Marca DD', '250 g', 'Tofu organico', 2.50, 'Tofu_1.png',
        'Tofu_2.png', 'Tofu_3.png'),
       ('Lentejas', 'Legumbres', 'Lentejas', NULL, 'Marca EE', '1 kg', 'Lentejas secas', 1.80, 'Lentejas_1.png',
        'Lentejas_2.png', 'Lentejas_3.png'),
       ('Garbanzos', 'Legumbres', 'Garbanzos', NULL, 'Marca FF', '1 kg', 'Garbanzos secos', 1.90, 'Garbanzos_1.png',
        'Garbanzos_2.png', 'Garbanzos_3.png'),
       ('Jugo de Naranja', 'Bebidas', 'Jugos', 'Natural', 'Marca GG', '1 litro', 'Jugo de naranja natural', 3.00,
        'Jugo de Naranja_1.png', 'Jugo de Naranja_2.png', 'Jugo de Naranja_3.png'),
       ('Cafe', 'Bebidas', 'Cafe', 'Molido', 'Marca HH', '250 g', 'Cafe molido', 4.00, 'Cafe_1.png', 'Cafe_2.png',
        'Cafe_3.png'),
       ('Te Verde', 'Bebidas', 'Te', 'Verde', 'Marca II', '20 bolsitas', 'Te verde organico', 2.50, 'Te Verde_1.png',
        'Te Verde_2.png', 'Te Verde_3.png'),
       ('Cereal', 'Desayuno', 'Cereales de Desayuno', NULL, 'Marca JJ', '500 g', 'Cereal integral', 3.20,
        'Cereal_1.png', 'Cereal_2.png', 'Cereal_3.png'),
       ('Granola', 'Desayuno', 'Cereales de Desayuno', NULL, 'Marca KK', '500 g', 'Granola con frutos secos', 4.00,
        'Granola_1.png', 'Granola_2.png', 'Granola_3.png'),
       ('Barra de Energia', 'Desayuno', 'Barras Energeticas', NULL, 'Marca LL', '50 g',
        'Barra de energia con chocolate', 1.20, 'Barra de Energia_1.png', 'Barra de Energia_2.png',
        'Barra de Energia_3.png'),
       ('Helado', 'Postres', 'Helados', 'Vainilla', 'Marca MM', '500 ml', 'Helado de vainilla', 3.50, 'Helado_1.png',
        'Helado_2.png', 'Helado_3.png'),
       ('Galletas', 'Postres', 'Galletas', 'Chocolate', 'Marca NN', '200 g', 'Galletas de chocolate', 2.00,
        'Galletas_1.png', 'Galletas_2.png', 'Galletas_3.png'),
       ('Chocolate', 'Postres', 'Chocolates', 'Oscuro', 'Marca OO', '100 g', 'Chocolate oscuro 70% cacao', 2.80,
        'Chocolate_1.png', 'Chocolate_2.png', 'Chocolate_3.png'),
       ('Salsa de Tomate', 'Condimentos', 'Salsas', 'Tomate', 'Marca PP', '500 g', 'Salsa de tomate para pasta', 1.50,
        'Salsa de Tomate_1.png', 'Salsa de Tomate_2.png', 'Salsa de Tomate_3.png'),
       ('Mayonesa', 'Condimentos', 'Salsas', 'Mayonesa', 'Marca QQ', '200 g', 'Mayonesa sin huevo', 1.80,
        'Mayonesa_1.png', 'Mayonesa_2.png', 'Mayonesa_3.png'),
       ('Mostaza', 'Condimentos', 'Salsas', 'Mostaza', 'Marca RR', '200 g', 'Mostaza Dijon', 2.00, 'Mostaza_1.png',
        'Mostaza_2.png', 'Mostaza_3.png'),
       ('Jabon Liquido', 'Higiene', 'Cuidado Personal', 'Jabon', 'Marca SS', '500 ml', 'Jabon liquido hidratante', 3.20,
        'Jabon Liquido_1.png', 'Jabon Liquido_2.png', 'Jabon Liquido_3.png'),
       ('Champu', 'Higiene', 'Cuidado Personal', 'Champu', 'Marca TT', '400 ml', 'Champu para cabello seco', 4.50,
        'Champu_1.png', 'Champu_2.png', 'Champu_3.png'),
       ('Papel Higienico', 'Higiene', 'Cuidado Personal', 'Papel', 'Marca UU', '12 rollos',
        'Papel higienico de 3 capas', 5.00, 'Papel Higienico_1.png', 'Papel Higienico_2.png', 'Papel Higienico_3.png'),
       ('Lysol Disinfectant Spray', 'Limpieza', 'Desinfectantes', 'Aerosol', 'Lysol', '500 g',
        'Spray desinfectante para superficies', 5.99, 'Lysol Disinfectant Spray_1.png',
        'Lysol Disinfectant Spray_2.png', 'Lysol Disinfectant Spray_3.png'),
       ('Clorox Bleach', 'Limpieza', 'Desinfectantes', 'Liquido', 'Clorox', '1000 g',
        'Blanqueador liquido para uso domestico', 3.99, 'Clorox Bleach_1.png', 'Clorox Bleach_2.png',
        'Clorox Bleach_3.png'),
       ('Windex Glass Cleaner', 'Limpieza', 'Limpiavidrios', 'Liquido', 'Windex', '650 g',
        'Limpiador de vidrios y superficies', 4.99, 'Windex Glass Cleaner_1.png', 'Windex Glass Cleaner_2.png',
        'Windex Glass Cleaner_3.png'),
       ('Mr. Clean Magic Eraser', 'Limpieza', 'Limpiadores Multiusos', 'Esponja', 'Mr. Clean', '50 g',
        'Esponja limpiadora multiusos', 2.99, 'Mr. Clean Magic Eraser_1.png', 'Mr. Clean Magic Eraser_2.png',
        'Mr. Clean Magic Eraser_3.png'),
       ('Pledge Furniture Polish', 'Limpieza', 'Limpiadores de Muebles', 'Aerosol', 'Pledge', '300 g',
        'Limpiador y abrillantador para muebles', 5.49, 'Pledge Furniture Polish_1.png',
        'Pledge Furniture Polish_2.png', 'Pledge Furniture Polish_3.png'),
       ('Swiffer WetJet', 'Limpieza', 'Mopas', 'Mopa', 'Swiffer', '1200 g', 'Mopa con sistema de limpieza humeda',
        24.99, 'Swiffer WetJet_1.png', 'Swiffer WetJet_2.png', 'Swiffer WetJet_3.png'),
       ('Tide Laundry Detergent', 'Limpieza', 'Detergentes', 'Liquido', 'Tide', '2500 g',
        'Detergente liquido para ropa', 12.99, 'Tide Laundry Detergent_1.png', 'Tide Laundry Detergent_2.png',
        'Tide Laundry Detergent_3.png'),
       ('Dawn Dish Soap', 'Limpieza', 'Lavaplatos', 'Liquido', 'Dawn', '700 g', 'Jabon liquido para lavar platos', 3.99,
        'Dawn Dish Soap_1.png', 'Dawn Dish Soap_2.png', 'Dawn Dish Soap_3.png'),
       ('Comet Cleaner with Bleach', 'Limpieza', 'Limpiadores Multiusos', 'Polvo', 'Comet', '600 g',
        'Limpiador multiusos en polvo con blanqueador', 1.99, 'Comet Cleaner with Bleach_1.png',
        'Comet Cleaner with Bleach_2.png', 'Comet Cleaner with Bleach_3.png'),
       ('iPhone 13', 'Electronica', 'Telefonos Moviles', 'iOS', 'Apple', '173 g',
        'Smartphone con pantalla de 6.1 pulgadas y 128GB de almacenamiento', 799.00, 'iPhone 13_1.png',
        'iPhone 13_2.png', 'iPhone 13_3.png'),
       ('MacBook Air M1', 'Electronica', 'Computadoras Portatiles', 'Ultrabook', 'Apple', '1.29 kg',
        'Ultrabook con chip M1 y 256GB de almacenamiento', 999.00, 'MacBook Air M1_1.png', 'MacBook Air M1_2.png',
        'MacBook Air M1_3.png'),
       ('iPad Pro', 'Electronica', 'Tablets', 'iOS', 'Apple', '682 g',
        'Tablet de 12.9 pulgadas con 128GB de almacenamiento', 1099.00, 'iPad Pro_1.png', 'iPad Pro_2.png',
        'iPad Pro_3.png'),
       ('Samsung Galaxy S21', 'Electronica', 'Telefonos Moviles', 'Android', 'Samsung', '169 g',
        'Smartphone con pantalla de 6.2 pulgadas y 128GB de almacenamiento', 799.99, 'Samsung Galaxy S21_1.png',
        'Samsung Galaxy S21_2.png', 'Samsung Galaxy S21_3.png'),
       ('Dell XPS 13', 'Electronica', 'Computadoras Portatiles', 'Ultrabook', 'Dell', '1.2 kg',
        'Ultrabook con procesador i7 y 512GB de almacenamiento', 1249.00, 'Dell XPS 13_1.png', 'Dell XPS 13_2.png',
        'Dell XPS 13_3.png'),
       ('Sony WH-1000XM4', 'Electronica', 'Audio', 'Auriculares', 'Sony', '254 g',
        'Auriculares inalambricos con cancelacion de ruido', 348.00, 'Sony WH-1000XM4_1.png', 'Sony WH-1000XM4_2.png',
        'Sony WH-1000XM4_3.png'),
       ('Bose SoundLink', 'Electronica', 'Audio', 'Altavoces', 'Bose', '660 g', 'Altavoz Bluetooth portatil', 129.00,
        'Bose SoundLink_1.png', 'Bose SoundLink_2.png', 'Bose SoundLink_3.png'),
       ('Logitech MX Master 3', 'Electronica', 'Perifericos', 'Raton', 'Logitech', '141 g',
        'Raton inalambrico ergonomico', 99.99, 'Logitech MX Master 3_1.png', 'Logitech MX Master 3_2.png',
        'Logitech MX Master 3_3.png'),
       ('Nintendo Switch', 'Electronica', 'Videojuegos', 'Consola', 'Nintendo', '297 g',
        'Consola de videojuegos hibrida', 299.99, 'Nintendo Switch_1.png', 'Nintendo Switch_2.png',
        'Nintendo Switch_3.png'),
       ('Sony PlayStation 5', 'Electronica', 'Videojuegos', 'Consola', 'Sony', '4.5 kg',
        'Consola de videojuegos de nueva generacion', 499.99, 'Sony PlayStation 5_1.png', 'Sony PlayStation 5_2.png',
        'Sony PlayStation 5_3.png'),
       ('Xbox Series X', 'Electronica', 'Videojuegos', 'Consola', 'Microsoft', '4.45 kg',
        'Consola de videojuegos de nueva generacion', 499.99, 'Xbox Series X_1.png', 'Xbox Series X_2.png',
        'Xbox Series X_3.png'),
       ('Google Nest Hub', 'Electronica', 'Domotica', 'Asistente Virtual', 'Google', '480 g',
        'Pantalla inteligente con Asistente de Google', 89.99, 'Google Nest Hub_1.png', 'Google Nest Hub_2.png',
        'Google Nest Hub_3.png'),
       ('Amazon Echo Dot', 'Electronica', 'Domotica', 'Asistente Virtual', 'Amazon', '300 g',
        'Altavoz inteligente con Alexa', 49.99, 'Amazon Echo Dot_1.png', 'Amazon Echo Dot_2.png',
        'Amazon Echo Dot_3.png'),
       ('Fitbit Charge 5', 'Electronica', 'Wearables', 'Reloj Inteligente', 'Fitbit', '28 g',
        'Reloj inteligente con monitor de actividad fisica', 179.95, 'Fitbit Charge 5_1.png', 'Fitbit Charge 5_2.png',
        'Fitbit Charge 5_3.png'),
       ('Samsung Galaxy Watch 4', 'Electronica', 'Wearables', 'Reloj Inteligente', 'Samsung', '30 g',
        'Reloj inteligente con monitor de salud', 249.99, 'Samsung Galaxy Watch 4_1.png',
        'Samsung Galaxy Watch 4_2.png', 'Samsung Galaxy Watch 4_3.png'),
       ('Microsoft Surface Pro 7', 'Electronica', 'Computadoras Portatiles', 'Convertible', 'Microsoft', '770 g',
        'Tablet con teclado desmontable y procesador i5', 749.99, 'Microsoft Surface Pro 7_1.png',
        'Microsoft Surface Pro 7_2.png', 'Microsoft Surface Pro 7_3.png'),
       ('Asus ROG Zephyrus G14', 'Electronica', 'Computadoras Portatiles', 'Gaming', 'Asus', '1.6 kg',
        'Laptop para juegos con procesador Ryzen 9 y GPU RTX 3060', 1449.99, 'Asus ROG Zephyrus G14_1.png',
        'Asus ROG Zephyrus G14_2.png', 'Asus ROG Zephyrus G14_3.png'),
       ('HP Envy 6055', 'Electronica', 'Impresoras', 'Multifuncion', 'HP', '5.22 kg',
        'Impresora multifuncion inalambrica', 129.99, 'HP Envy 6055_1.png', 'HP Envy 6055_2.png', 'HP Envy 6055_3.png'),
       ('DJI Mavic Air 2', 'Electronica', 'Drones', 'Drone', 'DJI', '570 g',
        'Drone con camara 4K y 34 minutos de vuelo', 799.00, 'DJI Mavic Air 2_1.png', 'DJI Mavic Air 2_2.png',
        'DJI Mavic Air 2_3.png'),
       ('Apple AirPods Pro', 'Electronica', 'Audio', 'Auriculares', 'Apple', '56.4 g',
        'Auriculares inalambricos con cancelacion de ruido', 249.00, 'Apple AirPods Pro_1.png',
        'Apple AirPods Pro_2.png', 'Apple AirPods Pro_3.png'),
       ('Google Pixel 6', 'Electronica', 'Telefonos Moviles', 'Android', 'Google', '207 g',
        'Smartphone con pantalla de 6.4 pulgadas y 128GB de almacenamiento', 599.00, 'Google Pixel 6_1.png',
        'Google Pixel 6_2.png', 'Google Pixel 6_3.png'),
       ('OnePlus 9 Pro', 'Electronica', 'Telefonos Moviles', 'Android', 'OnePlus', '197 g',
        'Smartphone con pantalla de 6.7 pulgadas y 256GB de almacenamiento', 969.00, 'OnePlus 9 Pro_1.png',
        'OnePlus 9 Pro_2.png', 'OnePlus 9 Pro_3.png'),
       ('Razer Blade 15', 'Electronica', 'Computadoras Portatiles', 'Gaming', 'Razer', '2.1 kg',
        'Laptop para juegos con procesador i7 y GPU RTX 3070', 1799.99, 'Razer Blade 15_1.png', 'Razer Blade 15_2.png',
        'Razer Blade 15_3.png'),
       ('Lenovo ThinkPad X1 Carbon', 'Electronica', 'Computadoras Portatiles', 'Ultrabook', 'Lenovo', '1.09 kg',
        'Ultrabook con procesador i7 y 1TB de almacenamiento', 1849.00, 'Lenovo ThinkPad X1 Carbon_1.png',
        'Lenovo ThinkPad X1 Carbon_2.png', 'Lenovo ThinkPad X1 Carbon_3.png'),
       ('Samsung Odyssey G9', 'Electronica', 'Monitores', 'Curvo', 'Samsung', '14.1 kg',
        'Monitor curvo de 49 pulgadas con resolucion 5120x1440', 1399.99, 'Samsung Odyssey G9_1.png',
        'Samsung Odyssey G9_2.png', 'Samsung Odyssey G9_3.png'),
       ('HP Omen 30L', 'Electronica', 'Computadoras de Escritorio', 'Gaming', 'HP', '12.86 kg',
        'PC para juegos con procesador i9 y GPU RTX 3080', 2199.99, 'HP Omen 30L_1.png', 'HP Omen 30L_2.png',
        'HP Omen 30L_3.png'),
       ('GoPro HERO9', 'Electronica', 'Fotografia', 'Camara de Accion', 'GoPro', '158 g',
        'Camara de accion con grabacion 5K', 399.99, 'GoPro HERO9_1.png', 'GoPro HERO9_2.png', 'GoPro HERO9_3.png'),
       ('Apple Watch Series 7', 'Electronica', 'Wearables', 'Reloj Inteligente', 'Apple', '32 g',
        'Reloj inteligente con pantalla siempre activa', 399.00, 'Apple Watch Series 7_1.png',
        'Apple Watch Series 7_2.png', 'Apple Watch Series 7_3.png'),
       ('Canon PIXMA G5020', 'Electronica', 'Impresoras', 'Inyeccion de Tinta', 'Canon', '6.5 kg',
        'Impresora de tanque de tinta inalambrica', 199.99, 'Canon PIXMA G5020_1.png', 'Canon PIXMA G5020_2.png',
        'Canon PIXMA G5020_3.png'),
       ('Sony A7 III', 'Electronica', 'Fotografia', 'Mirrorless', 'Sony', '650 g',
        'Camara mirrorless con sensor full-frame de 24 MP', 1999.99, 'Sony A7 III_1.png', 'Sony A7 III_2.png',
        'Sony A7 III_3.png'),
       ('NVIDIA Shield TV Pro', 'Electronica', 'Streaming', 'Set-top Box', 'NVIDIA', '250 g',
        'Dispositivo de streaming 4K HDR', 199.99, 'NVIDIA Shield TV Pro_1.png', 'NVIDIA Shield TV Pro_2.png',
        'NVIDIA Shield TV Pro_3.png'),
       ('Roku Streaming Stick+', 'Electronica', 'Streaming', 'Stick', 'Roku', '26 g',
        'Dispositivo de streaming 4K con control remoto', 49.99, 'Roku Streaming Stick+_1.png',
        'Roku Streaming Stick+_2.png', 'Roku Streaming Stick+_3.png'),
       ('Alienware AW3420DW', 'Electronica', 'Monitores', 'Curvo', 'Alienware', '11.8 kg',
        'Monitor curvo de 34 pulgadas con resolucion 3440x1440', 1199.99, 'Alienware AW3420DW_1.png',
        'Alienware AW3420DW_2.png', 'Alienware AW3420DW_3.png'),
       ('Western Digital My Passport', 'Electronica', 'Almacenamiento', 'Disco Duro Externo', 'Western Digital',
        '120 g', 'Disco duro externo de 4TB', 119.99, 'Western Digital My Passport_1.png',
        'Western Digital My Passport_2.png', 'Western Digital My Passport_3.png'),
       ('Kingston DataTraveler', 'Electronica', 'Almacenamiento', 'Memoria USB', 'Kingston', '10 g',
        'Memoria USB de 128GB', 29.99, 'Kingston DataTraveler_1.png', 'Kingston DataTraveler_2.png',
        'Kingston DataTraveler_3.png'),
       ('Anker PowerCore 10000', 'Electronica', 'Accesorios', 'Power Bank', 'Anker', '180 g',
        'Bateria portatil de 10000mAh', 25.99, 'Anker PowerCore 10000_1.png', 'Anker PowerCore 10000_2.png',
        'Anker PowerCore 10000_3.png'),
       ('TP-Link Archer AX50', 'Electronica', 'Redes', 'Router', 'TP-Link', '580 g', 'Router WiFi 6 dual band', 149.99,
        'TP-Link Archer AX50_1.png', 'TP-Link Archer AX50_2.png', 'TP-Link Archer AX50_3.png'),
       ('Nest Learning Thermostat', 'Electronica', 'Domotica', 'Termostato', 'Google', '240 g',
        'Termostato inteligente con control remoto', 249.00, 'Nest Learning Thermostat_1.png',
        'Nest Learning Thermostat_2.png', 'Nest Learning Thermostat_3.png'),
       ('Sony PlayStation VR', 'Electronica', 'Videojuegos', 'Realidad Virtual', 'Sony', '610 g',
        'Sistema de realidad virtual para PlayStation 4 y 5', 349.99, 'Sony PlayStation VR_1.png',
        'Sony PlayStation VR_2.png', 'Sony PlayStation VR_3.png'),
       ('Oculus Quest 2', 'Electronica', 'Realidad Virtual', 'Standalone', 'Oculus', '503 g',
        'Gafas de realidad virtual todo en uno', 299.00, 'Oculus Quest 2_1.png', 'Oculus Quest 2_2.png',
        'Oculus Quest 2_3.png'),
       ('Glock 19', 'Armas', 'Pistolas', 'Semiautomatica', 'Glock', '670 g',
        'Pistola semiautomatica de 9 mm con capacidad de 15 cartuchos', 600.00, 'Glock 19_1.png', 'Glock 19_2.png',
        'Glock 19_3.png'),
       ('Colt M1911', 'Armas', 'Pistolas', 'Semiautomatica', 'Colt', '1105 g',
        'Pistola semiautomatica de .45 ACP con capacidad de 7 cartuchos', 950.00, 'Colt M1911_1.png',
        'Colt M1911_2.png', 'Colt M1911_3.png'),
       ('Smith & Wesson Model 29', 'Armas', 'Revolveres', 'Magnum', 'Smith & Wesson', '1200 g',
        'Revolver de .44 Magnum con capacidad de 6 cartuchos', 1200.00, 'Smith & Wesson Model 29_1.png',
        'Smith & Wesson Model 29_2.png', 'Smith & Wesson Model 29_3.png'),
       ('Remington 870', 'Armas', 'Escopetas', 'Repetidora', 'Remington', '3500 g',
        'Escopeta de accion por bombeo de calibre 12', 450.00, 'Remington 870_1.png', 'Remington 870_2.png',
        'Remington 870_3.png'),
       ('Mossberg 500', 'Armas', 'Escopetas', 'Repetidora', 'Mossberg', '3500 g',
        'Escopeta de accion por bombeo de calibre 12', 400.00, 'Mossberg 500_1.png', 'Mossberg 500_2.png',
        'Mossberg 500_3.png'),
       ('AR-15', 'Armas', 'Rifles', 'Semiautomatico', 'Colt', '3100 g',
        'Rifle semiautomatico de 5.56 mm con capacidad de 30 cartuchos', 900.00, 'AR-15_1.png', 'AR-15_2.png',
        'AR-15_3.png'),
       ('AK-47', 'Armas', 'Rifles', 'Automatico', 'Kalashnikov', '4300 g',
        'Rifle automatico de 7.62 mm con capacidad de 30 cartuchos', 700.00, 'AK-47_1.png', 'AK-47_2.png',
        'AK-47_3.png'),
       ('M4 Carbine', 'Armas', 'Rifles', 'Semiautomatico', 'Colt', '2900 g',
        'Rifle semiautomatico de 5.56 mm con capacidad de 30 cartuchos', 1500.00, 'M4 Carbine_1.png',
        'M4 Carbine_2.png', 'M4 Carbine_3.png'),
       ('Barrett M82', 'Armas', 'Rifles', 'Francotirador', 'Barrett', '14500 g',
        'Rifle de francotirador de calibre .50 BMG', 8000.00, 'Barrett M82_1.png', 'Barrett M82_2.png',
        'Barrett M82_3.png'),
       ('Sig Sauer P226', 'Armas', 'Pistolas', 'Semiautomatica', 'Sig Sauer', '964 g',
        'Pistola semiautomatica de 9 mm con capacidad de 15 cartuchos', 900.00, 'Sig Sauer P226_1.png',
        'Sig Sauer P226_2.png', 'Sig Sauer P226_3.png'),
       ('Heckler & Koch MP5', 'Armas', 'Subfusiles', 'Automatico', 'Heckler & Koch', '2900 g',
        'Subfusil automatico de 9 mm con capacidad de 30 cartuchos', 2500.00, 'Heckler & Koch MP5_1.png',
        'Heckler & Koch MP5_2.png', 'Heckler & Koch MP5_3.png'),
       ('FN SCAR-H', 'Armas', 'Rifles', 'Automatico', 'FN Herstal', '3600 g',
        'Rifle automatico de 7.62 mm con capacidad de 20 cartuchos', 3500.00, 'FN SCAR-H_1.png', 'FN SCAR-H_2.png',
        'FN SCAR-H_3.png'),
       ('RPG-7', 'Armas', 'Lanzacohetes', 'Portatil', 'Bazalt', '7000 g', 'Lanzacohetes antitanque portatil', 1500.00,
        'RPG-7_1.png', 'RPG-7_2.png', 'RPG-7_3.png'),
       ('Desert Eagle', 'Armas', 'Pistolas', 'Semiautomatica', 'Magnum Research', '2000 g',
        'Pistola semiautomatica de .50 AE', 1500.00, 'Desert Eagle_1.png', 'Desert Eagle_2.png', 'Desert Eagle_3.png'),
       ('Mossberg 590', 'Armas', 'Escopetas', 'Repetidora', 'Mossberg', '3500 g',
        'Escopeta de accion por bombeo de calibre 12', 450.00, 'Mossberg 590_1.png', 'Mossberg 590_2.png',
        'Mossberg 590_3.png'),
       ('Benelli M4', 'Armas', 'Escopetas', 'Semiautomatica', 'Benelli', '3600 g',
        'Escopeta semiautomatica de calibre 12', 2000.00, 'Benelli M4_1.png', 'Benelli M4_2.png', 'Benelli M4_3.png'),
       ('Ruger 10/22', 'Armas', 'Rifles', 'Semiautomatico', 'Ruger', '2300 g',
        'Rifle semiautomatico de calibre .22 LR con capacidad de 10 cartuchos', 300.00, 'Ruger 10/22_1.png',
        'Ruger 10/22_2.png', 'Ruger 10/22_3.png'),
       ('CZ 75', 'Armas', 'Pistolas', 'Semiautomatica', 'CZ', '1000 g',
        'Pistola semiautomatica de 9 mm con capacidad de 16 cartuchos', 700.00, 'CZ 75_1.png', 'CZ 75_2.png',
        'CZ 75_3.png'),
       ('Walther P99', 'Armas', 'Pistolas', 'Semiautomatica', 'Walther', '700 g',
        'Pistola semiautomatica de 9 mm con capacidad de 15 cartuchos', 650.00, 'Walther P99_1.png',
        'Walther P99_2.png', 'Walt                       her P99_3.png'),
       ('Heckler & Koch G36', 'Armas', 'Rifles', 'Automatico', 'Heckler & Koch', '3600 g',
        'Rifle automatico de 5.56 mm con capacidad de 30 cartuchos', 1800.00, 'Heckler & Koch G36_1.png',
        'Heckler & Koch G36_2.png', 'Heckler & Koch G36_3.png'),
       ('Winchester Model 70', 'Armas', 'Rifles', 'Cerrojo', 'Winchester', '3400 g',
        'Rifle de cerrojo de calibre .30-06 Springfield', 800.00, 'Winchester Model 70_1.png',
        'Winchester Model 70_2.png', 'Winchester Model 70_3.png'),
       ('Taurus PT92', 'Armas', 'Pistolas', 'Semiautomatica', 'Taurus', '960 g',
        'Pistola semiautomatica de 9 mm con capacidad de 17 cartuchos', 500.00, 'Taurus PT92_1.png',
        'Taurus PT92_2.png', 'Taurus PT92_3.png'),
       ('Beretta 92FS', 'Armas', 'Pistolas', 'Semiautomatica', 'Beretta', '950 g',
        'Pistola semiautomatica de 9 mm con capacidad de 15 cartuchos', 600.00, 'Beretta 92FS_1.png',
        'Beretta 92FS_2.png', 'Beretta 92FS_3.png');
