INSERT INTO "producto" ("nombre", "categoria", "subcategoria", "subsubcategoria", "marca", "peso", "descripcion", "precio") VALUES
('Manzana', 'Frutas', 'Frutas Frescas', NULL, 'Marca A', '1 kg', 'Manzana roja fresca', 2.50),
('Banana', 'Frutas', 'Frutas Frescas', NULL, 'Marca B', '1 kg', 'Banana amarilla madura', 1.80),
('Pera', 'Frutas', 'Frutas Frescas', NULL, 'Marca A', '1 kg', 'Pera jugosa y dulce', 2.75),
('Leche', 'Lácteos', 'Leche', 'Entera', 'Marca C', '1 litro', 'Leche entera pasteurizada', 1.20),
('Yogurt', 'Lácteos', 'Yogurt', 'Natural', 'Marca D', '500 g', 'Yogurt natural sin azúcar', 1.50),
('Queso', 'Lácteos', 'Quesos', 'Fresco', 'Marca E', '250 g', 'Queso fresco de cabra', 3.40),
('Pan', 'Panadería', 'Panes', 'Integral', 'Marca F', '500 g', 'Pan integral con semillas', 2.20),
('Croissant', 'Panadería', 'Pasteles', 'Dulce', 'Marca G', '100 g', 'Croissant de mantequilla', 1.00),
('Bagel', 'Panadería', 'Panes', 'Clásico', 'Marca H', '100 g', 'Bagel clásico', 0.90),
('Arroz', 'Cereales', 'Arroz', 'Integral', 'Marca I', '1 kg', 'Arroz integral orgánico', 1.80),
('Harina', 'Cereales', 'Harinas', 'Trigo', 'Marca J', '1 kg', 'Harina de trigo todo uso', 1.20),
('Pasta', 'Cereales', 'Pasta', 'Spaghetti', 'Marca K', '500 g', 'Spaghetti de trigo duro', 1.00),
('Aceite de Oliva', 'Aceites', 'Aceites Vegetales', NULL, 'Marca L', '500 ml', 'Aceite de oliva extra virgen', 5.00),
('Mantequilla', 'Aceites', 'Mantequillas', NULL, 'Marca M', '200 g', 'Mantequilla sin sal', 2.50),
('Miel', 'Endulzantes', 'Mieles', NULL, 'Marca N', '250 g', 'Miel de abeja pura', 3.75),
('Azúcar', 'Endulzantes', 'Azúcar', 'Blanca', 'Marca O', '1 kg', 'Azúcar blanca refinada', 1.10),
('Sal', 'Condimentos', 'Sales', 'Marina', 'Marca P', '500 g', 'Sal marina fina', 0.80),
('Pimienta', 'Condimentos', 'Especias', 'Negra', 'Marca Q', '50 g', 'Pimienta negra molida', 1.50),
('Canela', 'Condimentos', 'Especias', 'Molida', 'Marca R', '50 g', 'Canela molida', 1.20),
('Tomate', 'Verduras', 'Vegetales Frescos', NULL, 'Marca S', '1 kg', 'Tomate rojo maduro', 2.30),
('Zanahoria', 'Verduras', 'Vegetales Frescos', NULL, 'Marca T', '1 kg', 'Zanahoria fresca', 1.50),
('Lechuga', 'Verduras', 'Vegetales Frescos', NULL, 'Marca U', '1 pieza', 'Lechuga romana', 1.20),
('Papas', 'Verduras', 'Tubérculos', NULL, 'Marca V', '1 kg', 'Papas blancas', 1.80),
('Cebolla', 'Verduras', 'Vegetales Frescos', NULL, 'Marca W', '1 kg', 'Cebolla amarilla', 1.50),
('Ajo', 'Verduras', 'Vegetales Frescos', NULL, 'Marca X', '200 g', 'Ajo blanco', 2.00),
('Pollo', 'Carnes', 'Aves', NULL, 'Marca Y', '1 kg', 'Pechuga de pollo fresca', 5.00),
('Res', 'Carnes', 'Carnes Rojas', NULL, 'Marca Z', '1 kg', 'Carne de res para asar', 7.50),
('Pescado', 'Pescados y Mariscos', 'Pescados', NULL, 'Marca AA', '1 kg', 'Filete de salmón', 10.00),
('Camarón', 'Pescados y Mariscos', 'Mariscos', NULL, 'Marca BB', '500 g', 'Camarones grandes', 8.00),
('Huevos', 'Huevos', 'Huevos de Gallina', NULL, 'Marca CC', '12 unidades', 'Huevos frescos', 2.40),
('Tofu', 'Proteínas Vegetales', 'Soja', NULL, 'Marca DD', '250 g', 'Tofu orgánico', 2.50),
('Lentejas', 'Legumbres', 'Lentejas', NULL, 'Marca EE', '1 kg', 'Lentejas secas', 1.80),
('Garbanzos', 'Legumbres', 'Garbanzos', NULL, 'Marca FF', '1 kg', 'Garbanzos secos', 1.90),
('Jugo de Naranja', 'Bebidas', 'Jugos', 'Natural', 'Marca GG', '1 litro', 'Jugo de naranja natural', 3.00),
('Café', 'Bebidas', 'Café', 'Molido', 'Marca HH', '250 g', 'Café molido', 4.00),
('Té Verde', 'Bebidas', 'Té', 'Verde', 'Marca II', '20 bolsitas', 'Té verde orgánico', 2.50),
('Cereal', 'Desayuno', 'Cereales de Desayuno', NULL, 'Marca JJ', '500 g', 'Cereal integral', 3.20),
('Granola', 'Desayuno', 'Cereales de Desayuno', NULL, 'Marca KK', '500 g', 'Granola con frutos secos', 4.00),
('Barra de Energía', 'Desayuno', 'Barras Energéticas', NULL, 'Marca LL', '50 g', 'Barra de energía con chocolate', 1.20),
('Helado', 'Postres', 'Helados', 'Vainilla', 'Marca MM', '500 ml', 'Helado de vainilla', 3.50),
('Galletas', 'Postres', 'Galletas', 'Chocolate', 'Marca NN', '200 g', 'Galletas de chocolate', 2.00),
('Chocolate', 'Postres', 'Chocolates', 'Oscuro', 'Marca OO', '100 g', 'Chocolate oscuro 70% cacao', 2.80),
('Salsa de Tomate', 'Condimentos', 'Salsas', 'Tomate', 'Marca PP', '500 g', 'Salsa de tomate para pasta', 1.50),
('Mayonesa', 'Condimentos', 'Salsas', 'Mayonesa', 'Marca QQ', '200 g', 'Mayonesa sin huevo', 1.80),
('Mostaza', 'Condimentos', 'Salsas', 'Mostaza', 'Marca RR', '200 g', 'Mostaza Dijon', 2.00),
('Jabón Líquido', 'Higiene', 'Cuidado Personal', 'Jabón', 'Marca SS', '500 ml', 'Jabón líquido hidratante', 3.20),
('Champú', 'Higiene', 'Cuidado Personal', 'Champú', 'Marca TT', '400 ml', 'Champú para cabello seco', 4.50),
('Papel Higiénico', 'Higiene', 'Cuidado Personal', 'Papel', 'Marca UU', '12 rollos', 'Papel higiénico de 3 capas', 5.00),
('Lysol Disinfectant Spray', 'Limpieza', 'Desinfectantes', 'Aerosol', 'Lysol', '500 g', 'Spray desinfectante para superficies', 5.99),
('Clorox Bleach', 'Limpieza', 'Desinfectantes', 'Líquido', 'Clorox', '1000 g', 'Blanqueador líquido para uso doméstico', 3.99),
('Windex Glass Cleaner', 'Limpieza', 'Limpiavidrios', 'Líquido', 'Windex', '650 g', 'Limpiador de vidrios y superficies', 4.99),
('Mr. Clean Magic Eraser', 'Limpieza', 'Limpiadores Multiusos', 'Esponja', 'Mr. Clean', '50 g', 'Esponja limpiadora multiusos', 2.99),
('Pledge Furniture Polish', 'Limpieza', 'Limpiadores de Muebles', 'Aerosol', 'Pledge', '300 g', 'Limpiador y abrillantador para muebles', 5.49),
('Swiffer WetJet', 'Limpieza', 'Mopas', 'Mopa', 'Swiffer', '1200 g', 'Mopa con sistema de limpieza húmeda', 24.99),
('Tide Laundry Detergent', 'Limpieza', 'Detergentes', 'Líquido', 'Tide', '2500 g', 'Detergente líquido para ropa', 12.99),
('Dawn Dish Soap', 'Limpieza', 'Lavaplatos', 'Líquido', 'Dawn', '700 g', 'Jabón líquido para lavar platos', 3.99),
('Comet Cleaner with Bleach', 'Limpieza', 'Limpiadores Multiusos', 'Polvo', 'Comet', '600 g', 'Limpiador multiusos en polvo con blanqueador', 1.99),
('iPhone 13', 'Electrónica', 'Teléfonos Móviles', 'iOS', 'Apple', '173 g', 'Smartphone con pantalla de 6.1 pulgadas y 128GB de almacenamiento', 799.00),
('MacBook Air M1', 'Electrónica', 'Computadoras Portátiles', 'Ultrabook', 'Apple', '1.29 kg', 'Ultrabook con chip M1 y 256GB de almacenamiento', 999.00),
('iPad Pro', 'Electrónica', 'Tablets', 'iOS', 'Apple', '682 g', 'Tablet de 12.9 pulgadas con 128GB de almacenamiento', 1099.00),
('Samsung Galaxy S21', 'Electrónica', 'Teléfonos Móviles', 'Android', 'Samsung', '169 g', 'Smartphone con pantalla de 6.2 pulgadas y 128GB de almacenamiento', 799.99),
('Dell XPS 13', 'Electrónica', 'Computadoras Portátiles', 'Ultrabook', 'Dell', '1.2 kg', 'Ultrabook con procesador i7 y 512GB de almacenamiento', 1249.00),
('Sony WH-1000XM4', 'Electrónica', 'Audio', 'Auriculares', 'Sony', '254 g', 'Auriculares inalámbricos con cancelación de ruido', 348.00),
('Bose SoundLink', 'Electrónica', 'Audio', 'Altavoces', 'Bose', '660 g', 'Altavoz Bluetooth portátil', 129.00),
('Logitech MX Master 3', 'Electrónica', 'Periféricos', 'Ratón', 'Logitech', '141 g', 'Ratón inalámbrico ergonómico', 99.99),
('Nintendo Switch', 'Electrónica', 'Videojuegos', 'Consola', 'Nintendo', '297 g', 'Consola de videojuegos híbrida', 299.99),
('Sony PlayStation 5', 'Electrónica', 'Videojuegos', 'Consola', 'Sony', '4.5 kg', 'Consola de videojuegos de nueva generación', 499.99),
('Xbox Series X', 'Electrónica', 'Videojuegos', 'Consola', 'Microsoft', '4.45 kg', 'Consola de videojuegos de nueva generación', 499.99),
('Google Nest Hub', 'Electrónica', 'Domótica', 'Asistente Virtual', 'Google', '480 g', 'Pantalla inteligente con Asistente de Google', 89.99),
('Amazon Echo Dot', 'Electrónica', 'Domótica', 'Asistente Virtual', 'Amazon', '300 g', 'Altavoz inteligente con Alexa', 49.99),
('Fitbit Charge 5', 'Electrónica', 'Wearables', 'Reloj Inteligente', 'Fitbit', '28 g', 'Reloj inteligente con monitor de actividad física', 179.95),
('Samsung Galaxy Watch 4', 'Electrónica', 'Wearables', 'Reloj Inteligente', 'Samsung', '30 g', 'Reloj inteligente con monitor de salud', 249.99),
('Microsoft Surface Pro 7', 'Electrónica', 'Computadoras Portátiles', 'Convertible', 'Microsoft', '770 g', 'Tablet con teclado desmontable y procesador i5', 749.99),
('Asus ROG Zephyrus G14', 'Electrónica', 'Computadoras Portátiles', 'Gaming', 'Asus', '1.6 kg', 'Laptop para juegos con procesador Ryzen 9 y GPU RTX 3060', 1449.99),
('HP Envy 6055', 'Electrónica', 'Impresoras', 'Multifunción', 'HP', '5.22 kg', 'Impresora multifunción inalámbrica', 129.99),
('DJI Mavic Air 2', 'Electrónica', 'Drones', 'Drone', 'DJI', '570 g', 'Drone con cámara 4K y 34 minutos de vuelo', 799.00),
('Apple AirPods Pro', 'Electrónica', 'Audio', 'Auriculares', 'Apple', '56.4 g', 'Auriculares inalámbricos con cancelación de ruido', 249.00),
('Google Pixel 6', 'Electrónica', 'Teléfonos Móviles', 'Android', 'Google', '207 g', 'Smartphone con pantalla de 6.4 pulgadas y 128GB de almacenamiento', 599.00),
('OnePlus 9 Pro', 'Electrónica', 'Teléfonos Móviles', 'Android', 'OnePlus', '197 g', 'Smartphone con pantalla de 6.7 pulgadas y 256GB de almacenamiento', 969.00),
('Razer Blade 15', 'Electrónica', 'Computadoras Portátiles', 'Gaming', 'Razer', '2.1 kg', 'Laptop para juegos con procesador i7 y GPU RTX 3070', 1799.99),
('Lenovo ThinkPad X1 Carbon', 'Electrónica', 'Computadoras Portátiles', 'Ultrabook', 'Lenovo', '1.09 kg', 'Ultrabook con procesador i7 y 1TB de almacenamiento', 1849.00),
('Samsung Odyssey G9', 'Electrónica', 'Monitores', 'Curvo', 'Samsung', '14.1 kg', 'Monitor curvo de 49 pulgadas con resolución 5120x1440', 1399.99),
('HP Omen 30L', 'Electrónica', 'Computadoras de Escritorio', 'Gaming', 'HP', '12.86 kg', 'PC para juegos con procesador i9 y GPU RTX 3080', 2199.99),
('GoPro HERO9', 'Electrónica', 'Fotografía', 'Cámara de Acción', 'GoPro', '158 g', 'Cámara de acción con grabación 5K', 399.99),
('Apple Watch Series 7', 'Electrónica', 'Wearables', 'Reloj Inteligente', 'Apple', '32 g', 'Reloj inteligente con pantalla siempre activa', 399.00),
('Canon PIXMA G5020', 'Electrónica', 'Impresoras', 'Inyección de Tinta', 'Canon', '6.5 kg', 'Impresora de tanque de tinta inalámbrica', 199.99),
('Sony A7 III', 'Electrónica', 'Fotografía', 'Mirrorless', 'Sony', '650 g', 'Cámara mirrorless con sensor full-frame de 24 MP', 1999.99),
('NVIDIA Shield TV Pro', 'Electrónica', 'Streaming', 'Set-top Box', 'NVIDIA', '250 g', 'Dispositivo de streaming 4K HDR', 199.99),
('Roku Streaming Stick+', 'Electrónica', 'Streaming', 'Stick', 'Roku', '26 g', 'Dispositivo de streaming 4K con control remoto', 49.99),
('Alienware AW3420DW', 'Electrónica', 'Monitores', 'Curvo', 'Alienware', '11.8 kg', 'Monitor curvo de 34 pulgadas con resolución 3440x1440', 1199.99),
('Western Digital My Passport', 'Electrónica', 'Almacenamiento', 'Disco Duro Externo', 'Western Digital', '120 g', 'Disco duro externo de 4TB', 119.99),
('Kingston DataTraveler', 'Electrónica', 'Almacenamiento', 'Memoria USB', 'Kingston', '10 g', 'Memoria USB de 128GB', 29.99),
('Anker PowerCore 10000', 'Electrónica', 'Accesorios', 'Power Bank', 'Anker', '180 g', 'Batería portátil de 10000mAh', 25.99),
('TP-Link Archer AX50', 'Electrónica', 'Redes', 'Router', 'TP-Link', '580 g', 'Router WiFi 6 dual band', 149.99),
('Nest Learning Thermostat', 'Electrónica', 'Domótica', 'Termostato', 'Google', '240 g', 'Termostato inteligente con control remoto', 249.00),
('Sony PlayStation VR', 'Electrónica', 'Videojuegos', 'Realidad Virtual', 'Sony', '610 g', 'Sistema de realidad virtual para PlayStation 4 y 5', 349.99),
('Oculus Quest 2', 'Electrónica', 'Realidad Virtual', 'Standalone', 'Oculus', '503 g', 'Gafas de realidad virtual todo en uno', 299.00),
('Glock 19', 'Armas', 'Pistolas', 'Semiautomática', 'Glock', '670 g', 'Pistola semiautomática de 9 mm con capacidad de 15 cartuchos', 600.00),
('Colt M1911', 'Armas', 'Pistolas', 'Semiautomática', 'Colt', '1105 g', 'Pistola semiautomática de .45 ACP con capacidad de 7 cartuchos', 950.00),
('Smith & Wesson Model 29', 'Armas', 'Revólveres', 'Magnum', 'Smith & Wesson', '1200 g', 'Revólver de .44 Magnum con capacidad de 6 cartuchos', 1200.00),
('Remington 870', 'Armas', 'Escopetas', 'Repetidora', 'Remington', '3500 g', 'Escopeta de acción por bombeo de calibre 12', 450.00),
('Mossberg 500', 'Armas', 'Escopetas', 'Repetidora', 'Mossberg', '3500 g', 'Escopeta de acción por bombeo de calibre 12', 400.00),
('AR-15', 'Armas', 'Rifles', 'Semiautomático', 'Colt', '3100 g', 'Rifle semiautomático de 5.56 mm con capacidad de 30 cartuchos', 900.00),
('AK-47', 'Armas', 'Rifles', 'Automático', 'Kalashnikov', '4300 g', 'Rifle automático de 7.62 mm con capacidad de 30 cartuchos', 700.00),
('M4 Carbine', 'Armas', 'Rifles', 'Semiautomático', 'Colt', '2900 g', 'Rifle semiautomático de 5.56 mm con capacidad de 30 cartuchos', 1500.00),
('Barrett M82', 'Armas', 'Rifles', 'Francotirador', 'Barrett', '14500 g', 'Rifle de francotirador de calibre .50 BMG', 8000.00),
('Sig Sauer P226', 'Armas', 'Pistolas', 'Semiautomática', 'Sig Sauer', '964 g', 'Pistola semiautomática de 9 mm con capacidad de 15 cartuchos', 900.00),
('Heckler & Koch MP5', 'Armas', 'Subfusiles', 'Automático', 'Heckler & Koch', '2900 g', 'Subfusil automático de 9 mm con capacidad de 30 cartuchos', 2500.00),
('FN SCAR-H', 'Armas', 'Rifles', 'Automático', 'FN Herstal', '3600 g', 'Rifle automático de 7.62 mm con capacidad de 20 cartuchos', 3500.00),
('RPG-7', 'Armas', 'Lanzacohetes', 'Portátil', 'Bazalt', '7000 g', 'Lanzacohetes antitanque portátil', 1500.00),
('Desert Eagle', 'Armas', 'Pistolas', 'Semiautomática', 'Magnum Research', '2000 g', 'Pistola semiautomática de .50 AE', 1500.00),
('Mossberg 590', 'Armas', 'Escopetas', 'Repetidora', 'Mossberg', '3500 g', 'Escopeta de acción por bombeo de calibre 12', 450.00),
('Benelli M4', 'Armas', 'Escopetas', 'Semiautomática', 'Benelli', '3600 g', 'Escopeta semiautomática de calibre 12', 2000.00),
('Ruger 10/22', 'Armas', 'Rifles', 'Semiautomático', 'Ruger', '2300 g', 'Rifle semiautomático de calibre .22 LR con capacidad de 10 cartuchos', 300.00),
('CZ 75', 'Armas', 'Pistolas', 'Semiautomática', 'CZ', '1000 g', 'Pistola semiautomática de 9 mm con capacidad de 16 cartuchos', 700.00),
('Walther P99', 'Armas', 'Pistolas', 'Semiautomática', 'Walther', '700 g', 'Pistola semiautomática de 9 mm con capacidad de 15 cartuchos', 650.00),
('Heckler & Koch G36', 'Armas', 'Rifles', 'Automático', 'Heckler & Koch', '3600 g', 'Rifle automático de 5.56 mm con capacidad de 30 cartuchos', 1800.00),
('Winchester Model 70', 'Armas', 'Rifles', 'Cerrojo', 'Winchester', '3400 g', 'Rifle de cerrojo de calibre .30-06 Springfield', 800.00),
('Taurus PT92', 'Armas', 'Pistolas', 'Semiautomática', 'Taurus', '960 g', 'Pistola semiautomática de 9 mm con capacidad de 17 cartuchos', 500.00),
('Beretta 92FS', 'Armas', 'Pistolas', 'Semiautomática', 'Beretta', '950 g', 'Pistola semiautomática de 9 mm con capacidad de 15 cartuchos', 600.00);

-- Insertamos paths de imagenes a la tabla imagen
INSERT INTO "imagen" ("codigo_producto", "path") VALUES
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Manzana'), 'Manzana_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Manzana'), 'Manzana_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Manzana'), 'Manzana_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Banana'), 'Banana_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Banana'), 'Banana_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Banana'), 'Banana_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pera'), 'Pera_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pera'), 'Pera_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pera'), 'Pera_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Leche'), 'Leche_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Leche'), 'Leche_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Leche'), 'Leche_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Yogurt'), 'Yogurt_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Yogurt'), 'Yogurt_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Yogurt'), 'Yogurt_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Queso'), 'Queso_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Queso'), 'Queso_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Queso'), 'Queso_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pan'), 'Pan_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pan'), 'Pan_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pan'), 'Pan_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Croissant'), 'Croissant_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Croissant'), 'Croissant_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Croissant'), 'Croissant_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Bagel'), 'Bagel_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Bagel'), 'Bagel_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Bagel'), 'Bagel_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Arroz'), 'Arroz_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Arroz'), 'Arroz_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Arroz'), 'Arroz_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Harina'), 'Harina_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Harina'), 'Harina_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Harina'), 'Harina_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pasta'), 'Pasta_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pasta'), 'Pasta_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pasta'), 'Pasta_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Aceite de Oliva'), 'Aceite de Oliva_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Aceite de Oliva'), 'Aceite de Oliva_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Aceite de Oliva'), 'Aceite de Oliva_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mantequilla'), 'Mantequilla_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mantequilla'), 'Mantequilla_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mantequilla'), 'Mantequilla_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Miel'), 'Miel_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Miel'), 'Miel_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Miel'), 'Miel_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Azúcar'), 'Azúcar_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Azúcar'), 'Azúcar_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Azúcar'), 'Azúcar_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sal'), 'Sal_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sal'), 'Sal_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sal'), 'Sal_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pimienta'), 'Pimienta_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pimienta'), 'Pimienta_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pimienta'), 'Pimienta_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Canela'), 'Canela_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Canela'), 'Canela_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Canela'), 'Canela_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Tomate'), 'Tomate_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Tomate'), 'Tomate_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Tomate'), 'Tomate_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Zanahoria'), 'Zanahoria_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Zanahoria'), 'Zanahoria_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Zanahoria'), 'Zanahoria_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lechuga'), 'Lechuga_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lechuga'), 'Lechuga_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lechuga'), 'Lechuga_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Papas'), 'Papas_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Papas'), 'Papas_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Papas'), 'Papas_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Cebolla'), 'Cebolla_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Cebolla'), 'Cebolla_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Cebolla'), 'Cebolla_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Ajo'), 'Ajo_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Ajo'), 'Ajo_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Ajo'), 'Ajo_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pollo'), 'Pollo_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pollo'), 'Pollo_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pollo'), 'Pollo_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Res'), 'Res_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Res'), 'Res_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Res'), 'Res_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pescado'), 'Pescado_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pescado'), 'Pescado_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pescado'), 'Pescado_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Camarón'), 'Camarón_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Camarón'), 'Camarón_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Camarón'), 'Camarón_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Huevos'), 'Huevos_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Huevos'), 'Huevos_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Huevos'), 'Huevos_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Tofu'), 'Tofu_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Tofu'), 'Tofu_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Tofu'), 'Tofu_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lentejas'), 'Lentejas_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lentejas'), 'Lentejas_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lentejas'), 'Lentejas_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Garbanzos'), 'Garbanzos_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Garbanzos'), 'Garbanzos_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Garbanzos'), 'Garbanzos_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Jugo de Naranja'), 'Jugo de Naranja_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Jugo de Naranja'), 'Jugo de Naranja_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Jugo de Naranja'), 'Jugo de Naranja_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Café'), 'Café_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Café'), 'Café_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Café'), 'Café_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Té Verde'), 'Té Verde_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Té Verde'), 'Té Verde_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Té Verde'), 'Té Verde_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Cereal'), 'Cereal_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Cereal'), 'Cereal_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Cereal'), 'Cereal_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Granola'), 'Granola_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Granola'), 'Granola_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Granola'), 'Granola_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Barra de Energía'), 'Barra de Energía_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Barra de Energía'), 'Barra de Energía_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Barra de Energía'), 'Barra de Energía_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Helado'), 'Helado_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Helado'), 'Helado_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Helado'), 'Helado_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Galletas'), 'Galletas_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Galletas'), 'Galletas_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Galletas'), 'Galletas_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Chocolate'), 'Chocolate_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Chocolate'), 'Chocolate_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Chocolate'), 'Chocolate_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Salsa de Tomate'), 'Salsa de Tomate_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Salsa de Tomate'), 'Salsa de Tomate_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Salsa de Tomate'), 'Salsa de Tomate_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mayonesa'), 'Mayonesa_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mayonesa'), 'Mayonesa_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mayonesa'), 'Mayonesa_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mostaza'), 'Mostaza_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mostaza'), 'Mostaza_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mostaza'), 'Mostaza_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Jabón Líquido'), 'Jabón Líquido_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Jabón Líquido'), 'Jabón Líquido_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Jabón Líquido'), 'Jabón Líquido_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Champú'), 'Champú_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Champú'), 'Champú_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Champú'), 'Champú_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Papel Higiénico'), 'Papel Higiénico_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Papel Higiénico'), 'Papel Higiénico_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Papel Higiénico'), 'Papel Higiénico_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lysol Disinfectant Spray'), 'Lysol Disinfectant Spray_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lysol Disinfectant Spray'), 'Lysol Disinfectant Spray_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lysol Disinfectant Spray'), 'Lysol Disinfectant Spray_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Clorox Bleach'), 'Clorox Bleach_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Clorox Bleach'), 'Clorox Bleach_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Clorox Bleach'), 'Clorox Bleach_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Windex Glass Cleaner'), 'Windex Glass Cleaner_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Windex Glass Cleaner'), 'Windex Glass Cleaner_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Windex Glass Cleaner'), 'Windex Glass Cleaner_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mr. Clean Magic Eraser'), 'Mr. Clean Magic Eraser_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mr. Clean Magic Eraser'), 'Mr. Clean Magic Eraser_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mr. Clean Magic Eraser'), 'Mr. Clean Magic Eraser_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pledge Furniture Polish'), 'Pledge Furniture Polish_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pledge Furniture Polish'), 'Pledge Furniture Polish_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Pledge Furniture Polish'), 'Pledge Furniture Polish_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Swiffer WetJet'), 'Swiffer WetJet_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Swiffer WetJet'), 'Swiffer WetJet_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Swiffer WetJet'), 'Swiffer WetJet_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Tide Laundry Detergent'), 'Tide Laundry Detergent_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Tide Laundry Detergent'), 'Tide Laundry Detergent_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Tide Laundry Detergent'), 'Tide Laundry Detergent_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Dawn Dish Soap'), 'Dawn Dish Soap_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Dawn Dish Soap'), 'Dawn Dish Soap_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Dawn Dish Soap'), 'Dawn Dish Soap_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Comet Cleaner with Bleach'), 'Comet Cleaner with Bleach_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Comet Cleaner with Bleach'), 'Comet Cleaner with Bleach_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Comet Cleaner with Bleach'), 'Comet Cleaner with Bleach_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'iPhone 13'), 'iPhone 13_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'iPhone 13'), 'iPhone 13_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'iPhone 13'), 'iPhone 13_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'MacBook Air M1'), 'MacBook Air M1_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'MacBook Air M1'), 'MacBook Air M1_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'MacBook Air M1'), 'MacBook Air M1_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'iPad Pro'), 'iPad Pro_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'iPad Pro'), 'iPad Pro_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'iPad Pro'), 'iPad Pro_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Samsung Galaxy S21'), 'Samsung Galaxy S21_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Samsung Galaxy S21'), 'Samsung Galaxy S21_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Samsung Galaxy S21'), 'Samsung Galaxy S21_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Dell XPS 13'), 'Dell XPS 13_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Dell XPS 13'), 'Dell XPS 13_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Dell XPS 13'), 'Dell XPS 13_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony WH-1000XM4'), 'Sony WH-1000XM4_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony WH-1000XM4'), 'Sony WH-1000XM4_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony WH-1000XM4'), 'Sony WH-1000XM4_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Bose SoundLink'), 'Bose SoundLink_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Bose SoundLink'), 'Bose SoundLink_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Bose SoundLink'), 'Bose SoundLink_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Logitech MX Master 3'), 'Logitech MX Master 3_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Logitech MX Master 3'), 'Logitech MX Master 3_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Logitech MX Master 3'), 'Logitech MX Master 3_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Nintendo Switch'), 'Nintendo Switch_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Nintendo Switch'), 'Nintendo Switch_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Nintendo Switch'), 'Nintendo Switch_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony PlayStation 5'), 'Sony PlayStation 5_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony PlayStation 5'), 'Sony PlayStation 5_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony PlayStation 5'), 'Sony PlayStation 5_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Xbox Series X'), 'Xbox Series X_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Xbox Series X'), 'Xbox Series X_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Xbox Series X'), 'Xbox Series X_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Google Nest Hub'), 'Google Nest Hub_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Google Nest Hub'), 'Google Nest Hub_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Google Nest Hub'), 'Google Nest Hub_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Amazon Echo Dot'), 'Amazon Echo Dot_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Amazon Echo Dot'), 'Amazon Echo Dot_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Amazon Echo Dot'), 'Amazon Echo Dot_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Fitbit Charge 5'), 'Fitbit Charge 5_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Fitbit Charge 5'), 'Fitbit Charge 5_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Fitbit Charge 5'), 'Fitbit Charge 5_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Samsung Galaxy Watch 4'), 'Samsung Galaxy Watch 4_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Samsung Galaxy Watch 4'), 'Samsung Galaxy Watch 4_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Samsung Galaxy Watch 4'), 'Samsung Galaxy Watch 4_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Microsoft Surface Pro 7'), 'Microsoft Surface Pro 7_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Microsoft Surface Pro 7'), 'Microsoft Surface Pro 7_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Microsoft Surface Pro 7'), 'Microsoft Surface Pro 7_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Asus ROG Zephyrus G14'), 'Asus ROG Zephyrus G14_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Asus ROG Zephyrus G14'), 'Asus ROG Zephyrus G14_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Asus ROG Zephyrus G14'), 'Asus ROG Zephyrus G14_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'HP Envy 6055'), 'HP Envy 6055_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'HP Envy 6055'), 'HP Envy 6055_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'HP Envy 6055'), 'HP Envy 6055_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'DJI Mavic Air 2'), 'DJI Mavic Air 2_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'DJI Mavic Air 2'), 'DJI Mavic Air 2_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'DJI Mavic Air 2'), 'DJI Mavic Air 2_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Apple AirPods Pro'), 'Apple AirPods Pro_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Apple AirPods Pro'), 'Apple AirPods Pro_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Apple AirPods Pro'), 'Apple AirPods Pro_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Google Pixel 6'), 'Google Pixel 6_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Google Pixel 6'), 'Google Pixel 6_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Google Pixel 6'), 'Google Pixel 6_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'OnePlus 9 Pro'), 'OnePlus 9 Pro_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'OnePlus 9 Pro'), 'OnePlus 9 Pro_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'OnePlus 9 Pro'), 'OnePlus 9 Pro_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Razer Blade 15'), 'Razer Blade 15_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Razer Blade 15'), 'Razer Blade 15_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Razer Blade 15'), 'Razer Blade 15_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lenovo ThinkPad X1 Carbon'), 'Lenovo ThinkPad X1 Carbon_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lenovo ThinkPad X1 Carbon'), 'Lenovo ThinkPad X1 Carbon_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Lenovo ThinkPad X1 Carbon'), 'Lenovo ThinkPad X1 Carbon_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Samsung Odyssey G9'), 'Samsung Odyssey G9_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Samsung Odyssey G9'), 'Samsung Odyssey G9_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Samsung Odyssey G9'), 'Samsung Odyssey G9_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'HP Omen 30L'), 'HP Omen 30L_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'HP Omen 30L'), 'HP Omen 30L_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'HP Omen 30L'), 'HP Omen 30L_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'GoPro HERO9'), 'GoPro HERO9_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'GoPro HERO9'), 'GoPro HERO9_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'GoPro HERO9'), 'GoPro HERO9_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Apple Watch Series 7'), 'Apple Watch Series 7_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Apple Watch Series 7'), 'Apple Watch Series 7_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Apple Watch Series 7'), 'Apple Watch Series 7_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Canon PIXMA G5020'), 'Canon PIXMA G5020_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Canon PIXMA G5020'), 'Canon PIXMA G5020_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Canon PIXMA G5020'), 'Canon PIXMA G5020_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony A7 III'), 'Sony A7 III_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony A7 III'), 'Sony A7 III_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony A7 III'), 'Sony A7 III_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'NVIDIA Shield TV Pro'), 'NVIDIA Shield TV Pro_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'NVIDIA Shield TV Pro'), 'NVIDIA Shield TV Pro_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'NVIDIA Shield TV Pro'), 'NVIDIA Shield TV Pro_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Roku Streaming Stick+'), 'Roku Streaming Stick+_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Roku Streaming Stick+'), 'Roku Streaming Stick+_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Roku Streaming Stick+'), 'Roku Streaming Stick+_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Alienware AW3420DW'), 'Alienware AW3420DW_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Alienware AW3420DW'), 'Alienware AW3420DW_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Alienware AW3420DW'), 'Alienware AW3420DW_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Western Digital My Passport'), 'Western Digital My Passport_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Western Digital My Passport'), 'Western Digital My Passport_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Western Digital My Passport'), 'Western Digital My Passport_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Kingston DataTraveler'), 'Kingston DataTraveler_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Kingston DataTraveler'), 'Kingston DataTraveler_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Kingston DataTraveler'), 'Kingston DataTraveler_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Anker PowerCore 10000'), 'Anker PowerCore 10000_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Anker PowerCore 10000'), 'Anker PowerCore 10000_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Anker PowerCore 10000'), 'Anker PowerCore 10000_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'TP-Link Archer AX50'), 'TP-Link Archer AX50_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'TP-Link Archer AX50'), 'TP-Link Archer AX50_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'TP-Link Archer AX50'), 'TP-Link Archer AX50_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Nest Learning Thermostat'), 'Nest Learning Thermostat_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Nest Learning Thermostat'), 'Nest Learning Thermostat_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Nest Learning Thermostat'), 'Nest Learning Thermostat_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony PlayStation VR'), 'Sony PlayStation VR_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony PlayStation VR'), 'Sony PlayStation VR_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sony PlayStation VR'), 'Sony PlayStation VR_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Oculus Quest 2'), 'Oculus Quest 2_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Oculus Quest 2'), 'Oculus Quest 2_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Oculus Quest 2'), 'Oculus Quest 2_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Glock 19'), 'Glock 19_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Glock 19'), 'Glock 19_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Glock 19'), 'Glock 19_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Colt M1911'), 'Colt M1911_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Colt M1911'), 'Colt M1911_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Colt M1911'), 'Colt M1911_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Smith & Wesson Model 29'), 'Smith & Wesson Model 29_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Smith & Wesson Model 29'), 'Smith & Wesson Model 29_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Smith & Wesson Model 29'), 'Smith & Wesson Model 29_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Remington 870'), 'Remington 870_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Remington 870'), 'Remington 870_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Remington 870'), 'Remington 870_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mossberg 500'), 'Mossberg 500_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mossberg 500'), 'Mossberg 500_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mossberg 500'), 'Mossberg 500_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'AR-15'), 'AR-15_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'AR-15'), 'AR-15_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'AR-15'), 'AR-15_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'AK-47'), 'AK-47_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'AK-47'), 'AK-47_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'AK-47'), 'AK-47_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'M4 Carbine'), 'M4 Carbine_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'M4 Carbine'), 'M4 Carbine_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'M4 Carbine'), 'M4 Carbine_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Barrett M82'), 'Barrett M82_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Barrett M82'), 'Barrett M82_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Barrett M82'), 'Barrett M82_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sig Sauer P226'), 'Sig Sauer P226_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sig Sauer P226'), 'Sig Sauer P226_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Sig Sauer P226'), 'Sig Sauer P226_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Heckler & Koch MP5'), 'Heckler & Koch MP5_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Heckler & Koch MP5'), 'Heckler & Koch MP5_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Heckler & Koch MP5'), 'Heckler & Koch MP5_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'FN SCAR-H'), 'FN SCAR-H_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'FN SCAR-H'), 'FN SCAR-H_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'FN SCAR-H'), 'FN SCAR-H_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'RPG-7'), 'RPG-7_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'RPG-7'), 'RPG-7_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'RPG-7'), 'RPG-7_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Desert Eagle'), 'Desert Eagle_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Desert Eagle'), 'Desert Eagle_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Desert Eagle'), 'Desert Eagle_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mossberg 590'), 'Mossberg 590_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mossberg 590'), 'Mossberg 590_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Mossberg 590'), 'Mossberg 590_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Benelli M4'), 'Benelli M4_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Benelli M4'), 'Benelli M4_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Benelli M4'), 'Benelli M4_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Ruger 10/22'), 'Ruger 10/22_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Ruger 10/22'), 'Ruger 10/22_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Ruger 10/22'), 'Ruger 10/22_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'CZ 75'), 'CZ 75_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'CZ 75'), 'CZ 75_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'CZ 75'), 'CZ 75_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Walther P99'), 'Walther P99_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Walther P99'), 'Walther P99_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Walther P99'), 'Walther P99_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Heckler & Koch G36'), 'Heckler & Koch G36_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Heckler & Koch G36'), 'Heckler & Koch G36_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Heckler & Koch G36'), 'Heckler & Koch G36_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Winchester Model 70'), 'Winchester Model 70_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Winchester Model 70'), 'Winchester Model 70_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Winchester Model 70'), 'Winchester Model 70_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Taurus PT92'), 'Taurus PT92_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Taurus PT92'), 'Taurus PT92_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Taurus PT92'), 'Taurus PT92_3.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Beretta 92FS'), 'Beretta 92FS_1.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Beretta 92FS'), 'Beretta 92FS_2.png'),
((SELECT "codigo" FROM "producto" WHERE "nombre" = 'Beretta 92FS'), 'Beretta 92FS_3.png');
