<%@page pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome to Costly</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="styles/default.css" rel="stylesheet">
  <link href="styles/costco-icons.css" rel="stylesheet">
</head>
<body class="default-theme">
  <jsp:include page="header.jsp"/>

  <div class="container-xxl my-3">
    <!-- URL -->
    <ul id="url" class="d-flex text-gray fs-7">
      <li><a class="url-link" href="/">Inicio</a></li>
      <li>Aviso de Privacidad</li>
    </ul>

    <div class="container-fluid row mb-5">
      <img class="img-fluid" src="img/aviso-de-privacidad.avif">
      <h2 class="my-4">Conozca sus derechos</h2>
      <div class="accordion d-flex flex-column row-gap-3">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="p-4 accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#collapse1">
              <b>Términos y condiciones</b>
            </button>
          </h2>
          <div id="collapse1" class="accordion-collapse collapse">
            <div class="accordion-body">
              Los presentes Términos y Condiciones (los "Términos y Condiciones") son aplicables a todas las personas que utilizan este sitio web, localizado en www.costco.com.mx (el "Sitio web" o la "Tienda en Línea"). Estos Términos y Condiciones constituyen las condiciones generales de contratación y conjuntamente con las Órdenes de Compra, las Confirmaciones de Compra correspondientes y los demás Documentos Contractuales del Sitio, rigen la relación que existe entre Costco de México, S.A. de C.V. ("Costco México", "Costco" o "Nosotros") y: (i) los Socios de Costco que utilizan el Sitio web y adquieren mercancías a través de medios electrónicos y/o (ii) las personas que visitan el Sitio web y consultan o usan su contenido (los "Usuarios"). Por favor lea cuidadosamente estos Términos y Condiciones. Al hacer uso de este Sitio web Usted manifiesta que ha leído y entendido los Documentos Contractuales del Sitio y que acepta obligarse conformidad con las declaraciones y cláusulas que los mismos establecen.<br>
              <br>
              <strong>1. Antecedentes</strong><br>
              Costco México ha desarrollado la Tienda en Línea para que cualquier Socio de Costco, localizado en México o en el extranjero, pueda adquirir alguno de los artículos contemplados en nuestro Catálogo de Artículos en Línea y solicitar que dichos artículos sean entregados en cualquier domicilio localizado en México. El uso de este Sitio web se rige por la legislación de los Estados Unidos Mexicanos. Si Usted usa este sitio desde otro país, Usted estará utilizando nuestro Sitio web bajo su propio riesgo y es responsable de cumplir con las leyes mexicanas y aquellas que se encuentran en vigor en la jurisdicción en la que Usted se ubica.<br>
              <br>
              <strong>2. Declaraciones de Costco México</strong><br>
              Costco México declara: (i) que Costco México es una sociedad mercantil constituida de conformidad con las leyes de los Estados Unidos Mexicanos; (ii) que Costco México opera diversas Tiendas de Autoservicio, localizadas en diversos puntos del territorio nacional; (iii) que Costco México tiene como actividad primordial de negocios el vender a sus afiliados las mercancías y los servicios que Costco México tiene en existencia en sus Tiendas de Autoservicio y; (iv) que Costco México ha desarrollado su Tienda en Línea con el propósito de que los Socios de Costco puedan adquirir a través de medios electrónicos las mercancías que se muestran en el Catálogo de Artículos en Línea en nuestro Sitio web, en los términos que las partes acuerden en la Orden de Compra y la Confirmación de Compra correspondientes.<br>
              <br>
              <strong>3. Declaraciones del Socio de Costco</strong><br>
              El Socio de Costco declara, por su propio derecho: (i) ser una persona física, mayor de 18 años de edad y contar con plena capacidad jurídica para poder obligarse en términos del presente contrato: (ii) ostentar la calidad de Socio de Costco; (iii) tener su domicilio ubicado, para efectos de este contrato, en la dirección que ha proporcionado a Costco México en su solicitud de afiliación o en el registro de su cuenta en línea; (iv) que desea registrarse en el Sitio web para crear una cuenta que se encuentre asociada a su membresía y le permita adquirir artículos de la Tienda en Línea; (v) que se encuentra consciente de que todas las transacciones que sean realizadas en el Sitio web por sí mismo o por un tercero y que se encuentren asociadas al uso de sus contraseñas y/o de su firma electrónica, serán atribuibles al Socio de Costco.<br>
              <br>
              En adición a las anteriores declaraciones el Socio de Costco que haya obtenido una afiliación dentro del programa de membresía "Negocio", manifiesta que: (a) tiene una relación jurídica con el negocio o empresa correspondiente la cual ha acreditado al momento de celebrar su Contrato de Afiliación y; (b) que en los términos de dicha relación jurídica, el Socio de Costco está facultado para actuar en nombre y representación de dicha empresa o negocio y/o para asumir obligaciones por la empresa o negocio correspondiente.<br>
              <br>
              <strong>4. Definiciones</strong><br>
              Los términos que se describen a continuación tendrán el significado que se les atribuye; lo anterior, ya sea que se utilicen con mayúsculas o minúsculas, en singular o plural o de forma abreviada.<br>
              <br>
              "Catálogo de Artículos en Línea" o "Catálogo".- Está conformado por todas las mercancías, bienes (incluyendo comida, vinos y licores), certificados de regalo y, en su caso, servicios, que se encuentran disponibles en la Tienda en Línea; los artículos del Catálogo no necesariamente se encuentran disponibles o en existencia al momento en que se realiza un Pedido; asimismo, pueden ser cambiados, substituidos o descontinuados de tiempo en tiempo a discreción de Costco México.<br>
              <br>
              "Contenidos del Sitio".- Este término incluye cualquier información o material contenido o publicado en el Sitio web. Comprende, de manera enunciativa más no limitativa: marcas, diseños, descripciones de productos, texto en lenguaje HTML, gráficas, archivos, fotografías o imágenes; también comprende el código, los programas de cómputo, representaciones de software, bases de datos y cualquier obra derivada que el Sitio web utiliza.<br>
              <br>
              "Contrato de Afiliación".- Es el Contrato de Afiliación que es celebrado entre Costco México y la persona que ha solicitado su afiliación. El Contrato de Afiliación, debidamente aceptado por Costco México confirma la afiliación del Socio de Costco a las Tiendas de Autoservicio operadas por Costco México y permite al titular de la membresía y a los titulares adicionales o complementarios designados por el Socio de Costco gozar de los beneficios de la membresía Costco.<br>
              <br>
              "Confirmación de Compra" o "Confirmación de Pedido".- Es el mensaje de datos generado por el Sitio web en el cual Costco México manifiesta su aceptación para surtir la Orden de Compra propuesta por el Socio de Costco. La Confirmación de Compra confirma que Costco México ha vendido y el Socio de Costco ha comprado los artículos correspondientes y hace constar el momento de la compra. El mensaje incluye un número de orden para que el Socio de Costco pueda monitorear la entrega de su pedido.<br>
              <br>
              "Documentos Contractuales del Sitio".- El término incluye a estos Términos y Condiciones, el Aviso de Privacidad, la Política de Entrega, Devoluciones y Cancelaciones (incluida la Garantía de Satisfacción Costco) y, en lo que resulte aplicable, el Contrato de Afiliación; en general, el término comprende también cualquier otro contrato, convenio, aviso o política que Costco México emita y publique de tiempo en tiempo y que sea aplicable a las transacciones que se realizan a través de la Tienda en Línea.<br>
              <br>
              "Empresas del Grupo Costco" o "Costco".- Este término incluye a Costco México y a todas las sociedades que pertenecen al grupo corporativo del cual forma parte Costco México, incluyendo a Costco Wholesale Corporation y Price Costco International Inc. y cualquier otra filial o subsidiaria de Costco México. "Garantía de Satisfacción Costco".- Es la política de Costco que permite a los Socios Costco poder realizar la devolución de artículos adquiridos y recibir la devolución de su dinero; esta política se describe en la Política de Entrega, Devoluciones y Cancelaciones.<br>
              <br>
              "Orden de Compra" o "Pedido".- Es el mensaje de datos generado por el Socio de Costco para solicitar la adquisición de un artículo del Catálogo de Artículos en Línea, y en el cual el Socio de Costco manifiesta su voluntad de adquirir dichos artículos en la cantidad, precio, términos y condiciones ahí establecidos.<br>
              <br>
              "Socio de Costco".- El término incluye a cualquier persona que haya obtenido la membresía de Costco, en cualquiera de sus modalidades, ya sea "Dorada", de "Negocio" y/o "Ejecutiva", en los términos de los programas correspondientes. En el caso de los Socios de Costco que se han afiliado a Costco en México, el término incluye a los socios que han celebrado un Contrato de Afiliación ya sea en alguno de los Almacenes o a través del Sitio web. En el caso de Socios de Costco no afiliados a Costco México, se considera como Socio de Costco a cualquier individuo o entidad que sea considerado como Socio por cualquiera de las Empresas del Grupo Costco.<br>
              <br>
              "Tiendas de Autoservicio".- "Sucursales" o "Almacenes".- Estos términos se utilizan de manera indistinta para referirse a cualquiera de las tiendas de autoservicio operadas por Costco México dentro del territorio de la República Mexicana.<br>
              <br>
              "Usuario".- Cualquier persona que visita y/o usa el Sitio Web por cualquier motivo. El término incluye a los Socios de Costco, en todo lo referente al uso que los Socios de Costco hacen del Sitio web.<br>
              <br>
              "Usted".- El término comprende de manera general a los Socios Costco y a cualquier Usuario, salvo que específicamente se exprese lo contrario.<br>
              <br>
              <strong>5. Objeto</strong><br>
              Los presentes Términos y Condiciones, conjuntamente con los Documentos Contractuales del Sitio establecen las condiciones generales de contratación que son aplicables: (i) de manera supletoria a las operaciones de compraventa que se llevan a cabo entre Costco México y los Socios de Costco en la Tienda en Línea y; (ii) al uso que Usted hace del Sitio web y del Contenido del Sitio.<br>
              <br>
              <strong>6. Restricciones de acceso o de uso aplicacbles en el Sitio</strong><br>
              a. Sitio exclusivo para Socios de Costco. Cualquier persona puede visitar y consultar las páginas del Sitio web. Sin embargo, únicamente los Socios de Costco pueden realizar compras de artículos en línea. Los Socios de Costco que deseen adquirir mercancías deberán registrarse al Sitio web para efectos de abrir una cuenta utilizando para tal efecto su número de membresía. Las Usuarios que no cuenten con una membresía podrán adquirir su membresía en cualquiera de las Sucursales de Costco México o celebrar un Contrato de Afiliación con Costco México a través del Sitio Web.<br>
              <br>
              b. Entregas de artículos únicamente en México. Este Sitio web sólo puede ser utilizado para adquirir artículos que vayan a ser entregados en algún domicilio localizado en México.<br>
              <br>
              c. Restricción para menores de edad e incapaces. Para registrarse y comprar en este Sitio web Usted debe tener al menos 18 años de edad. Costco México no fomenta ni permite de manera consciente que menores de edad puedan hacer uso de este Sitio web. Si Usted no ha cumplido 18 años o su capacidad contractual está limitada por la legislación aplicable, Usted no debe hacernos llegar Órdenes de Compra o utilizar de manera alguna nuestro Sitio web.<br>
              <br>
              <strong>7. Licencia para el uso del Sitio web; usos permitidos y restricciones</strong> <br>
              Si Usted cumple con los requisitos anteriormente señalados y no está sujeto a alguna de las restricciones referidas en la Cláusula 6 anterior, Costco México le otorga una licencia personal, no exclusiva, revocable e intransferible para que Usted pueda usar nuestro Sitio web para uso exclusivamente personal, privado y sin fines de lucro.<br>
              <br>
              Esta licencia se encuentra sujeta a restricciones y no incluye, entre otros, los siguientes usos: (i) utilizar el Sitio web para revender productos o hacer cualquier otro uso comercial del Sitio web o de los Contenidos del Sitio; (ii) llevar a cabo la modificación, adaptación, traducción, reversión de ingeniería, desensamblaje, descompilación o conversión de cualquier formato o programa de cómputo que exista del Sitio web. Usted solo está autorizado para utilizar el código HTML o cualquier otro código de este Sitio web en la forma en que Usted lo recibe a través de su navegador; tampoco queda autorizado para poner dichos códigos a disposición de un tercero; (iii) copiar, imitar, replicar para su uso en servidores espejo, reproducir, distribuir, publicar, descargar, mostrar o transmitir cualquier Contenido del Sitio (incluyendo marcas registradas) en cualquier forma o por cualquier medio; esta restricción incluye, pero no se limita a los siguientes medios: medios electrónicos, mecánicos, medios de fotocopiado, grabación o cualquier otro medio; (iv) recopilar y usar cualquier listado de productos o descripciones de productos; (v) hacer modificaciones al Sitio Web y/o a los Contenidos del Sitio o realizar cualquier obra derivada a partir de dichos materiales o; (vi) utilizar cualquier mecanismo o herramienta automatizada (incluyendo bots, spiders entre otros) o cualquier método o tecnología similar que tenga como finalidad o como consecuencia, el realizar la extracción, obtención o recopilación, directa o indirecta, de los Contenidos del Sitio, o de cualquier información o datos personales relacionados con el Sitio web. Excepto por los usos del Sitio web que han sido autorizados en esta cláusula, se hace notar que Costco México no le otorga a Usted de manera explícita o implícita, derecho o licencia alguna para que Usted pueda utilizar cualquier patente, marca registrada, derecho de autor, derechos de acceso, uso o explotación de bases de datos o cualquier otro derecho de propiedad intelectual que pertenezca a las Empresas del Grupo Costco o a cualquier tercero, en los términos de la legislación aplicable (incluyendo derechos de autor o de propiedad industrial). Usted no debe utilizar meta-tags o texto oculto que incluya el nombre, marca registrada o los nombres de los productos de las Empresas del Grupo Costco sin obtener previamente consentimiento expreso y por escrito de Costco México.<br>
              <br>
              Costco México se reserva el derecho de dar por terminada la presente licencia en cualquier momento si Usted incumple con cualquiera de las cláusulas establecidas en los Documentos Contractuales del Sitio o si permite o tolera que un tercero incumpla con dichas cláusulas. En dicho caso, Costco México puede cancelar su cuenta en nuestro Sitio web y prohibirle el acceso o uso del mismo, así como cancelar su membresía, de conformidad con lo establecido en el Contrato de Afiliación y el Reglamento. Se hace notar que la realización de conductas que contravengan las cláusulas establecidas en los Documentos Contractuales del Sitio puede resultar también en una violación a la ley (incluyendo la legislación en materia de derechos de autor, propiedad industrial, leyes mercantiles, de telecomunicaciones o legislación penal, entre otras disposiciones). Costco México se reserva su derecho de ejercer en contra de Usted cualquier acción de carácter mercantil, penal, civil o administrativa que conforme al derecho proceda, para defender los derechos de Costco México o de cualquier Usuario del Sitio.<br>
              <br>
              <strong>8. Compraventa de mercancías; contratación y pago de artículos</strong><br>
              a. Uso de contraseña. Al crear una cuenta en el Sitio web, nuestra plataforma vinculará su número de membresía de socio con su dirección de correo electrónico y con la contraseña de seguridad que Usted elegirá y que sólo Usted debe conocer. De esta manera, su contraseña queda asociada a su identidad y perfil de Socio dentro del Sitio web. Usted solamente podrá realizar transacciones si ha ingresado al Sitio web mediante el uso de su contraseña secreta. En términos de las disposiciones contenidas en el Código de Comercio, el uso de esta contraseña nos permite identificarlo en el ambiente digital y atribuirle los actos y transacciones que realiza en la Tienda en Línea. Costco México tiene derecho: (i) a asumir que los mensajes de datos asociados a su firma electrónica o cuenta provienen del Socio de Costco vinculado a dicha firma y/o cuenta y a actuar en consecuencia del mensaje recibido (v.g. procesar una compra de mercancías) y; (ii) a considerar que el mensaje de datos que nos hizo llegar corresponde expresamente al que Usted nos quiso hacer llegar.<br>
              <br>
              b. Información entregada al Socio Costco antes de la transacción. Antes de realizar su Pedido, Usted podrá revisar las características y especificaciones técnicas de la mercancía y los términos y condiciones que son aplicables a la adquisición del artículo (incluyendo el precio, cargos, métodos de pago, y condiciones especiales que podrían ser aplicables a la entrega de la mercancía). Esta información aparece generalmente en las fichas de información asociadas a cada producto. De manera supletoria, toda compraventa de artículos está regida por los presentes Términos y Condiciones y por la Política de Entrega, Devoluciones y Cancelaciones misma que incluye la Garantía de Satisfacción Costco. En caso de que Usted tenga alguna duda respecto de la mercancía o el servicio que pretende adquirir, por favor póngase en contacto con Costco México. Antes de hacer su Pedido, nuestra Tienda en Línea le permitirá revisar los artículos que ha seleccionado, la cantidad que productos que ha elegido comprar y el domicilio en el cual se realizará la entrega, además del precio total a ser pagado y los impuestos que corresponden a la transacción.<br>
              <br>
              c. Precios. Los precios de los artículos están expresados en pesos, la Moneda de curso legal en los Estados Unidos Mexicanos. Los precios de los artículos son los que muestran en el Sitio web y, salvo que se indique lo contrario, incluyen los impuestos aplicables, los gastos de envío y entrega y, en su caso, los cargos y gastos relacionados con la importación de los productos. En caso de mercancía cuyo precio total se determine en función de su peso, Usted no deberá pagar un precio adicional en caso de recibir un producto de mayor peso. Antes de hacer clic en el botón de pago, Usted podrá ver el precio total a ser pagado y los descuentos que pudieran ser aplicables; los impuestos a ser pagados aparecerán desglosados en los términos que establezca la regulación aplicable.<br>
              <br>
              d. Disponibilidad de artículos. Los artículos que se muestran en el Sitio web pertenecen a nuestro Catálogo de Artículos en Línea. Los artículos están sujetos a disponibilidad y, por lo tanto, es posible que no se encuentren en existencia al momento de que Usted realice el Pedido. Por favor considere el hecho de que los artículos se encuentren en el Catálogo en el Sitio web no constituye una oferta unilateral de venta de estas mercancías por parte de Costco México. Por el contrario, cuando Usted nos hace llegar una Orden de Compra, Usted realiza una oferta para adquirir de nosotros una determinada cantidad de mercancías. En caso de que nosotros aceptemos su oferta, Usted recibirá un mensaje de datos de Confirmación de Compra. Por lo general, si no contamos con existencia suficiente de mercancías o requerimos información adicional de su parte para procesar la transacción, hacemos de su conocimiento estas situaciones antes de enviarle una Confirmación de Compra.<br>
              <br>
              e. Compraventa de artículos; propiedad de las mercancías. La compraventa se perfecciona y es obligatoria para ambas partes en el momento en que Usted recibe de Costco México un mensaje de Confirmación de Compra a través del Sitio web; por lo general, nosotros realizamos el cargo en su tarjeta de crédito al momento en que emitimos su Confirmación de Compra. La propiedad de las mercancías le es transmitida en el momento en que Usted recibe la Confirmación de Compra o en el momento en que Costco México recibe su pago, independientemente de si el pago fue pactado en parcialidades o de manera total.<br>
              f. Riesgos de pérdida o deterioro del artículo.- Usted es responsable de la pérdida, daño o deterioro de su mercancía a partir del momento en que se realiza la entrega de la mercancía. La mercancía se considera entregada cuando la empresa de mensajería la pone a disposición del destinatario en el domicilio establecido para la entrega y cuando el destinatario firma de recibido.<br>
              <br>
              g. Entrega de las mercancías.- Los términos aplicables a la entrega de las mercancías varían dependiendo del tipo de artículo adquirido y de su tamaño. En general, los artículos se entregan en los términos señalados en la Política de Entrega, Devoluciones y Cancelaciones y en los Términos de Entrega que le fueron informados en la ficha del artículo correspondiente. Costco México no asume responsabilidad por retrasos en la entrega o imposibilidad de realizar la entrega cuando dichos retrasos o imposibilidad de cumplimiento derive de algún caso fortuito, fuerza mayor y, en general, de cualquier causa fuera del control de Costco México. En todo caso, la máxima responsabilidad de Costco por cualquier incumplimiento de entrega será la que se establece como pena convencional en estos Términos Y Condiciones. En caso de que la empresa de mensajería no logre entregar el artículo en tres visitas al Socio de Costco, el artículo será regresado a Costco México.<br>
              <br>
              h. Cancelación de Órdenes de Compra por parte de Costco México. El Socio de Costco y Costco México aceptan que Costco México gozará del derecho de rescindir o cancelar total o parcialmente cualquier transacción con posterioridad a la Confirmación de Compra y hasta antes de la entrega. En este caso, Costco México se pondrá en contacto con Usted y le hará saber que su orden fue cancelada. En los casos en que se determine la cancelación de una orden, no le haremos el cargo a su tarjeta de crédito o bien, le informaremos que su Pedido ha sido cancelado y reembolsaremos su dinero a la tarjeta de crédito que se utilizó como medio de pago. El Socio de Costco acepta que Costco México rescinda o cancele la compra y realice la devolución del dinero correspondiente cuando la cancelación se derive de, o se haya originado por, entre otras, las siguientes situaciones:<br>
              <br>
              i. Errores tipográficos o de captura;<br>
              <br>
              ii. Fallas en los sistemas informáticos de Costco México o de sus proveedores;<br>
              <br>
              iii. La existencia de imprecisiones o errores en la información ofrecida para alguna mercancía en nuestro Catálogo, o respecto de su precio o disponibilidad;<br>
              <br>
              iv. Acciones tomadas por Costco México para garantizar la equidad entre Socios de Costco en caso de que varios socios soliciten los mismos artículos y la existencia de los mismos sea limitada;<br>
              <br>
              v. Posibles riesgos relacionados con Usted o su método de pago que sean identificados por nuestros departamentos de crédito o prevención de fraudes;<br>
              <br>
              vi. Situaciones fuera del control de Costco México que limiten o impidan la entrega de alguna mercancía.<br>
              <br>
              vii. En caso de que Costco México determine que Usted ha incumplido con alguno de los términos establecidos en los Documentos Contractuales del Sitio.<br>
              <br>
              i. Garantía de Satisfacción Costco; devoluciones y cancelaciones.- Costco México ofrece una garantía total de satisfacción a sus socios respecto de los productos adquiridos. Los Socios de Costco tienen derecho a cancelar las transacciones realizadas a través de medios electrónicos y a solicitar la devolución de los artículos adquiridos y la devolución del precio pagado en los términos de nuestras políticas. Usted tiene derecho a preferir reemplazar su mercancía en vez de una devolución en caso de que Costco México tenga existencia de la misma mercancía. Este derecho aplica: (i) en la compra de artículos en la Tienda en Línea; (ii) al pago de cuotas de afiliación o renovación de afiliación, en términos de la Cláusula Vigésima Novena del Contrato de Afiliación. Para mayor información acerca de los procedimientos para realizar devoluciones por favor consulte nuestra Política de Entregas, Devoluciones y Cancelaciones.<br>
              <br>
              j. Pagos en línea.- Nuestro sistema de pago en línea acepta únicamente pagos a través de tarjetas de crédito Visa, MasterCard, American Express y Costco. Antes de poder completar su Orden de Compra, Usted deberá haber proporcionado a través del Sitio web el domicilio asociado a su tarjeta y los datos asociados a su tarjeta de crédito, incluyendo su número de tarjeta, el nombre del titular, la fecha de vencimiento y el código de seguridad de la tarjeta. Para algunos artículos o durante periodos de promociones especiales, Usted recibirá la opción de pagar a meses sin intereses. Los términos específicos de pago le serán informados en las fichas de información del artículo. Se hace notar que Costco México no almacena la información de su tarjeta de crédito; estos datos son obtenidos directamente de Usted, a través de una sección protegida por altos niveles de seguridad en nuestro Sitio web, por la empresa que hemos contratado para realizar el procesamiento de pagos. El procesador de pagos solicita la autorización de su compra al banco emisor. Costco México ha adoptado diversas medidas para asegurarse de que su pago en línea de se realice de manera segura y confiable. Para mayor información, consulte nuestro Aviso de Privacidad.<br>
              <br>
              k. Facturas electrónicas.- Una vez que Usted reciba su Confirmación de Compra, Usted recibirá la opción de solicitar su factura. Para tal efecto, por favor haga clic en el botón "Solicitar Factura"; su factura electrónica le será enviada a su dirección de correo electrónico. Si desea facturar posteriormente su compra en línea o hecha en sucursal, ingrese a la sección "Facturación Electrónica", misma en donde podrá solicitar su factura. Su factura le será enviada regularmente 24 horas después de que Usted la haya solicitado.<br>
              <br>
              l. Términos aplicables a la afiliación o renovación de membresías. Para obtener su afiliación como socio, Usted deberá seguir el procedimiento de contratación correspondiente en el Sitio web; durante este proceso Costco México le presentará el Contrato de Afiliación correspondiente, mismo que Usted deberá leer y aceptar antes de completar su afiliación. Los términos que aplican a la relación entre Costco y Usted para efectos de su relación como Socio de Costco son aquellos que se especifican en el Contrato de Afiliación. Se hace notar que, como en cualquier otra transacción realizada a través del Sitio, Costco México se reserva el derecho de rechazar su solicitud de afiliación o cualquier solicitud de renovación por cualquier causa y sin responsabilidad alguna para Costco México.<br>
              <br>
              <strong>9. Información contenida en nuestro Catálogo; disponibilidad de artículos</strong><br>
              Costco México realiza esfuerzos para asegurar que la descripción de las mercancías o servicios que se incluye en nuestro Catálogo sea precisa, asimismo, para asegurar que los productos se encuentren disponibles al precio especificado. Sin embargo, el Socio de Costco acepta que en la medida permitida por las leyes, Costco México:<br>
              <br>
              a. No se compromete a que la información del Catálogo (incluyendo las descripciones de productos, fotografías, guías de usuario, etiquetas, garantías) o cualquier Contenido del Sitio resulten exactos, se encuentren completos, sean fiables, se encuentren actualizados o libres de errores u omisiones; tampoco se compromete a que dicha información coincida exactamente con la información de las etiquetas, garantías o cualquier otra información incluida en, o adjunta a, los artículos mismos o sus empaques.<br>
              <br>
              b. Se reserva el derecho de cambiar o sustituir, en cualquier momento, cualquier artículo del Catálogo, los precios o especificaciones publicados en el Sitio y cualquier otro Contenido del Sitio; por lo general, realizaremos estas modificaciones de tiempo en tiempo, sin previo aviso; no asumimos responsabilidad por los daños o perjuicios que pudieran causarle el cambio, sustitución o la discontinuidad de un artículo;<br>
              <br>
              c. Tiene el derecho de revocar cualquier oferta o promoción aplicable a las mercancías, incluso antes de que concluya la vigencia de la promoción; en todo caso, Costco México notificará la revocación de la oferta o promoción a través del Sitio web. Costco México respetará los derechos de los consumidores cuyas órdenes hayan sido aceptadas durante la vigencia de la oferta o promoción en los términos de la regulación aplicable;<br>
              <br>
              d. No garantiza que los bienes o servicios que se encuentran incluidos en nuestro Catálogo estarán disponibles cuando Usted nos envíe su Orden de Compra o posteriormente;<br>
              <br>
              e. Se reserva el derecho de limitar las cantidades de mercancías puestas a disposición para la venta a través del Sitio, en la medida que la ley lo permita.<br>
              <br>
              <strong>10. Otras obligaciones de los Usuarios</strong><br>
              <br>
              <strong>11. Los Socios de Costco y los Usuarios del Sitio web asumen las siguientes obligaciones:</strong><br>
              a. Cumplir con todas las cláusulas contenidas en estos Términos y Condiciones y en los Documentos Contractuales del Sitio.<br>
              <br>
              b. Proveer al Sitio web información completa, correcta y actualizada. El Usuario se obliga a notificar a Costco México cualquier cambio en la información previamente proporcionada (incluyendo direcciones de entrega). Para tal efecto, por favor utilice las opciones que Costco México ofrece para corregir sus datos personales en términos de nuestro Aviso de Privacidad. <br>
              <br>
              c. Mantener de manera secreta y confidencial su contraseña de acceso al Sitio web y cualquier otro dato de creación de su firma electrónica. En caso de que Usted considere que ha perdido el control sobre la confidencialidad de su cuenta o de su contraseña o dicha confidencialidad se encuentra en riesgo, notifique esta situación inmediatamente a Costco México contactando a nuestro Centro de Atención a Socios para Compras en Línea. Usted es responsable de cualquier transacción que sea realizada a través de su cuenta (hecha por Usted mismo o por un tercero) ocurrida hasta antes de que Usted nos haya notificado esta situación. Costco México no asume obligación alguna con respecto a estas transacciones.<br>
              <br>
              d. El Usuario se obliga a no utilizar el Sitio web para: (i) participar en, fomentar o hacer apología de un delito; para realizar acciones que violen los derechos de terceros o que resulten en la violación de algún ley nacional o internacional; (ii) hacerse pasar por otra persona u entidad o usar de manera falsa o fraudulenta cualquier derecho asociado a su membresía, y (iii) difundir a través de la plataforma del Sitio web cualquier información, programa o código que pudiera causar un daño incluyendo un virus, troyanos, gusanos u otros códigos de programación informática que pudieran dañar, espiar, interferir, interceptar o extraer información o datos personales de nuestros sistemas informáticos, de la plataforma sobre la que opera la tienda en línea, o de los equipos, redes, sistemas y programas de cómputo que utilicen nuestros Usuarios para interactuar con el Sitio web.<br>
              <br>
              Costco México opera este Sitio web; sin embargo, no tiene capacidad para monitorear que las diversas personas y entidades que participan en el Sitio web cumplan con las leyes aplicables; por lo tanto, Costco México no asume responsabilidad alguna por cualquier contenido publicado o cargado al Sitio web por terceros incluyendo contenidos que pudieran dar lugar a error, difamación, calumnia, omisión, amenazas, falsedad o que pudieran ser considerados como de carácter pornográfico o que hagan apología o fomenten algún acto ilícito. Costco México tiene el derecho de (pero no se encuentra obligado a) investigar cualquier conducta de un Usuario que sea reportada o percibida como ilegal o que pudiera contravenir alguna de las cláusulas contenidas en los Documentos Contractuales del Sitio; Costco México puede realizar esta investigación por iniciativa propia o a solicitud de un tercero. Si Usted considera que una conducta violatoria de algún derecho está sucediendo en nuestro Sitio web (incluyendo alguna violación de marcas, derechos de autor o de alguna otra ley), por favor envíenos un correo a <a href="mailto:webmaster@costco.com.mx">webmaster@costco.com.mx</a> o llámenos al siguiente teléfono: 55 5200 8214.<br>
              <br>
              Costco México se reserva el derecho de adoptar las acciones técnicas o legales que considere adecuadas para proteger los intereses de Costco o los derechos de terceros. Estas medidas incluyen la emisión de advertencias a algún Usuario o el suspender, interrumpir o cancelar el acceso o uso que un Socio de Costco o un Usuario hagan del Sitio web.<br>
              <br>
              Usted se obliga a indemnizar a Costco México y sus empleados y representantes con respecto a cualquier daño o perjuicio que Costco México sea obligado a pagar como consecuencia de algún reclamo, acción o demanda que sea entablada en el contrato de Costco México por algún tercero, cuando dicha demanda o acción se funde en, o se relacione con, el uso que Usted ha hecho del Sitio web o su incumplimiento de cualquiera de las Términos y Condiciones del Sitio web o de los derechos de terceros. Usted deberá reembolsar a Costco México cualesquiera gastos que Costco México deba erogar con relación a dichos reclamos o demandas, incluyendo costos de multas y gastos en honorarios legales.<br>
              <br>
              <strong>12. Medidas de Seguridad</strong><br>
              Costco México se reserva el derecho de tomar acciones unilaterales (incluyendo el dar de baja, desactivar o inhabilitar la cuenta de cualquier Socio de Costco o inhabilitar su contraseña en cualquier momento) cuando dichas acciones resulten necesarias para mantener la seguridad del Sitio web y/o de las cuentas de los Socios de Costco; también podemos solicitar información adicional de Usted a empresas que nos apoyan en procesos de prevención e investigación de fraudes, para efectos de evaluar si debemos o no autorizar o cancelar una transacción.<br>
              <br>
              Costco México ha adoptado medidas de seguridad técnicas, físicas y administrativas para proteger su cuenta y el Sitio web; sin embargo, nosotros no podemos proteger su información fuera del Sitio web. En este sentido, por ejemplo, si nosotros nos comunicamos con Usted vía electrónica pero utilizando algún mecanismo externo al Sitio web (v.g. correo electrónico) Usted reconoce y acepta que existe un riesgo de que dicha comunicación pudiera no ser transmitida y/o almacenada de forma segura, y pudiera ser conocida por algún tercero. Si Usted nos solicita información a través de correo electrónico, la información que le hagamos llegar en nuestra respuesta podría estar siendo transmitida o almacenada sin utilizar técnicas de criptografía o cifrado. Del mismo modo los correos electrónicos que Usted nos envíe pueden no hallarse protegidos por técnicas de cifrado y, por lo tanto, pueden ser, vistos o accedidos por terceros.<br>
              <br>
              Por favor, consulte nuestro Aviso de Privacidad para obtener más información sobre cómo usamos, obtenemos, almacenamos, transferimos y protegemos sus datos personales.<br>
              <br>
              <strong>13. Propiedad intelectual</strong><br>
              a. Propiedad de los Contenidos del Sitio. Todos los Contenidos del Sitio son propiedad de las Empresas del Grupo Costco o de los fabricantes o proveedores y se encuentran protegidos en México y en otros países por leyes en materia de derechos de autor y propiedad industrial y por tratados internaciones en materia de propiedad intelectual.<br>
              <br>
              b. Marcas Registradas. COSTCO, COSTCO.COM.MX, KIRKLAND SIGNATURE, y sus respectivos diseños y logotipos son marcas registradas propiedad de las Empresas del Grupo Costco y no pueden ser copiadas, imitadas o usadas, en todo o en parte, sin la autorización previa y por escrito de las Empresas del Grupo Costco. Asimismo, los encabezados de página, los gráficos personalizados, los íconos de los botones y los guiones o textos constituyen también propiedad intelectual de Costco y se encuentran protegidos por derechos marcarios; por lo tanto, no pueden ser copiados, imitados o utilizados, en todo o en parte, sin nuestra autorización previa y por escrito. Se hace notar que entre el Contenido del Sitio también existen marcas registradas, nombres de productos y logotipos, entre otros, que son propiedad de sus respectivos dueños. Usted no puede utilizar dichos derechos de propiedad intelectual sin la autorización correspondiente.<br>
              <br>
              c. Restricciones de Uso. Salvo que así se indique de manera expresa en los Documentos Contractuales del Sitio, ningún Contenido del Sitio o cualquier otro material protegido por las leyes de propiedad intelectual o industrial relacionado con el Sitio web puede ser copiado, reproducido, distribuido, replicado, descargado, mostrado, publicado o transmitido en cualquier forma o por cualquier medio, sin nuestra autorización previa y por escrito o sin la autorización previa y por escrito del propietario de los derechos de propiedad intelectual; lo anterior incluye, pero no se limita al uso de medios electrónicos, mecánicos, de fotocopiado, grabación o cualquier otro. Usted puede copiar electrónicamente e imprimir algunos materiales de este Sitio web para uso personal y privado y sin fines comerciales o de lucro. Queda prohibido cualquier otro uso de los materiales en este Sitio web sin nuestro permiso previo y por escrito.<br>
              <br>
              d. Programas de Cómputo (Software).Todo programa de cómputo, incluyendo cualquier archivo, imágenes incorporadas o generadas por el software, y cualesquiera datos que acompañan al programa de cómputo (el "Software") que pudieran estar disponibles a través del Sitio web o facilitar su operación podrán ser utilizados únicamente en términos de la licencia que le hemos concedido en estos Términos y Condiciones. Las Empresas del Grupo Costco conservarán en todo momento todos los derechos propiedad intelectual con respecto al Software. Usted no debe copiar, distribuir, vender, modificar, descompilar, realizar ingeniería inversa, desensamblar o crear adaptaciones, modificaciones u obras derivadas a partir de nuestro Software sin autorización expresa y por escrito de las Empresas del Grupo Costco.<br>
              <br>
              <strong>14. Hipervínculos</strong><br>
              a. Enlaces permitidos hacia nuestro Sitio web. Costco México permite crear un hipervínculo que enlace alguna página web de un tercero única y exclusivamente a la página principal de nuestro Sitio web; el derecho que se otorga no es exclusivo y se concede siempre y cuando el hipervínculo no implique el representar a alguna de las Empresas del Grupo Costco o a cualquiera de sus productos y servicios de una forma despectiva, falsa, engañosa o difamatoria. El derecho que se concede está sujeto a restricciones y puede ser revocado por Costco México en cualquier momento. Queda prohibido el utilizar cualquier Contenido del Sitio protegido por los derechos de propiedad intelectual o industrial de las Empresas del Grupo Costco (incluyendo marcas, textos, diseño de cualquier página o formulario) sin nuestro consentimiento previo y por escrito. Lo anterior, incluyendo el uso de cualquier material por medio de técnicas de enmarcado (framing). Cualquier otra forma de vinculación entre nuestro Sitio web y otro sitio sin nuestro consentimiento previo y por escrito se encuentra prohibido. Salvo que se haga constar expresamente, el derecho conferido en esta cláusula no confiere el otorgamiento implícito o explícito de licencia alguna en favor de alguna persona o entidad.<br>
              <br>
              b. Enlace entre nuestro Sitio web y páginas web de terceros. Nuestro Sitio web ofrece a los Usuarios hipervínculos que les permiten acceder a páginas web de terceros, a quienes les hemos autorizado el que utilicen dicha tecnología para ofertar productos, servicios o alguna información. Se hace notar que Costco México no tiene control sobre dichas páginas web de terceros y, por lo tanto, no podemos asumir, ni asumimos responsabilidad alguna respecto del contenido de dichas páginas o por sus prácticas en materia de protección de datos personales. Se advierte al Usuario que el hecho de que permitamos la existencia de estos enlaces no implica que nosotros hayamos aprobado o respaldemos estas páginas web o cualquier información que las mismas contengan. No ofrecemos garantía alguna respecto de las páginas web de terceros y no asumimos responsabilidad por la calidad, exactitud o fiabilidad de los contenidos ahí incluidos.<br>
              <br>
              <strong>15. Riesgos de utilizar el Sitio web; no se otorgan garantías</strong><br>
              Todo Usuario del Sitio acepta que utiliza el Sitio web bajo su propio riesgo. Este Sitio web y los materiales contenidos en el mismo se proporcionan tal cual se encuentran y, en la medida permitida por la ley aplicable, sin garantías de ningún tipo. Costco México no otorga garantía alguna, explícita o implícita respecto de la calidad o idoneidad de la información o respecto de la idoneidad del Sitio web o su contenido para un propósito particular; Costco México no garantiza de manera implícita o explícita que el uso del Sitio web satisfaga los requerimientos del Usuario o que los materiales en este Sitio web sean exactos, fiables o se encuentren completos o actualizados o libres de error. Costco México no es responsable por errores tipográficos u omisiones relacionados con los precios, textos o fotografías. Costco México no garantiza que este Sitio web o su servidor (es) se encuentren libres de virus u otros componentes nocivos inclusive si Costco o sus representantes han sido advertidos de la posibilidad de la existencia de tales virus u otros componentes dañinos. Le recomendamos utilizar algún software de detección de virus de los que se encuentran disponibles en el mercado al acceder o utilizar este Sitio web y mantener dicho software actualizado. La referencia a cualquier producto, servicio, proceso u otra información, por su nombre comercial, marca registrada, fabricante, proveedor o cualquier otro no constituye o implica respaldo, patrocinio o recomendación de los mismos por Costco.<br>
              <br>
              <strong>16. Limitación de responsabilidades</strong><br>
              Costco México ofrece a sus socios la Garantía de Satisfacción Costco respecto de las mercancías adquiridas. Esta garantía se describe en términos generales en nuestra Política de Entrega, Devoluciones y Cancelaciones. Hasta donde resulta permitido conforme a la legislación aplicable, Costco México no asume responsabilidad alguna por cualesquiera daños o perjuicios que pudieran ser ocasionados a un Socio de Costco o algún Usuario: (i) por el uso del Sitio web o bien por la imposibilidad de usar el Sitio web o la interrupción o discontinuidad de nuestro servicio de Tienda en Línea; (ii) por el actualización o falta de actualización del Contenido del Sitio o por la imprecisión de alguna información; (iii) por las transacciones que se realicen con tarjetas de crédito que han sido reportadas como robadas; lo anterior en virtud de que Costco México no conserva datos de su tarjeta, sino que únicamente recibe la aprobación del banco emisor respecto de la transacción.<br>
              <br>
              Todo uso de los productos adquiridos por parte del Socio Costco es responsabilidad exclusiva de la persona que utiliza la mercancía. Una vez que el producto es entregado a su destinatario, el usuario es responsable de la forma en que utiliza los artículos.<br>
              <br>
              A pesar de lo establecido en el párrafo anterior, si se determinara que Costco México es responsable ante Usted, cualquiera que sea la causa, nuestra responsabilidad frente a Usted o algún tercero, las partes de este contrato aceptan que esta responsabilidad se encuentra limitada por la pena convencional que este acto acuerdan Costco México y el Socio de Costco. Las partes acuerdan que dicha pena convencional será equivalente a la cantidad por el precio total que Usted nos haya pagado por concepto de su Orden de Compra.<br>
              <br>
              Las estipulaciones establecidas en esta cláusula no excluyen la responsabilidad que pudiera derivarse para Costco México en su carácter de vendedor de los artículos o la responsabilidad civil que pudiera suscitarse en términos de la legislación aplicable.<br>
              <br>
              <strong>17. Terminación</strong><br>
              Costco México se reserva el derecho de dar por terminado en cualquier momento la licencia que concede para el uso de este Sitio Web. El Contrato de Afiliación y los demás Documentos Contractuales del Sitio subsistirán a la terminación de la licencia.<br>
              <br>
              <strong>18. Cesión de derechos y obligaciones</strong><br>
              El Socio de Costco y el Usuario no podrán ceder los derechos y obligaciones que se establecen a su cargo en los presentes Términos y Condiciones y en cualquier otro Documento Contractual del Sitio; los Socios de Costco México conceden desde este momento a Costco México autorización para que Costco México pueda ceder a un tercero los derechos y obligaciones que a cargo de Costco México se derivan de estos Términos y Condiciones.<br>
              <br>
              <strong>19. Modificaciones</strong><br>
              Costco México podrá modificar los presentes Términos y Condiciones y en general, los Documentos Contractuales del Sitio de tiempo en tiempo. En dicho caso, publicaremos la nueva versión del documento modificado en el Sitio web y haremos notar en dicho documento la fecha en que se realizó la última actualización. Si consideramos que las modificaciones propuestas resultan sustanciales para nuestra relación con Usted, haremos un esfuerzo por notificarle (v.g. a través de una comunicación a su último correo electrónico registrado) el hecho de que Costco ha realizado modificaciones.<br>
              <br>
              Cualquier cambio o modificación entrará en vigor en un plazo de 30 días naturales contados a partir de la fecha en que se publique la versión modificada. Si Usted no está de acuerdo con los nuevos Documentos Contractuales del Sitio, por favor deje de utilizar el Sitio web. Al hacer uso de nuestro Sitio web con posterioridad a la entrada en vigor de cualquiera de nuestros Documentos Contractuales del Sitio, Usted está manifestando su consentimiento con respecto a las cláusulas contenidas en los mismos. Sin perjuicio de lo anterior, se hace notar que las modificaciones no serán aplicadas de manera retroactiva a las órdenes que se encuentran en proceso de entrega, mismas que continuarán rigiéndose por los Documentos Contractuales del Sitio que se encontraban vigentes al momento de realizar la Confirmación de Compra.<br>
              <br>
              <strong>20. Validez por separado de las cláusulas; renuncias</strong><br>
              En caso de que cualquier cláusula contenida en los Documentos Contractuales del Sitio sea declarada como ilegal, nula, no puesta o inexigible entonces en la medida que la legislación lo permita, dicha ilegalidad, nulidad, invalidez o inexigibilidad no afectará la validez de las demás cláusulas establecidas en los Documentos Contractuales del Sitio, mismas que continuarán siendo exigibles entre las partes.<br>
              <br>
              <strong>21. Renuncias de derechos</strong><br>
              El hecho de que Costco México no ejerza total o parcialmente algún derecho establecido en los Documentos Contractuales del Sitio no deberá ser interpretado como una renuncia a tal derecho. Cualquier renuncia de derechos hecha por Costco México deberá constar por escrito.<br>
              <br>
              <strong>22. Derechos de terceros</strong><br>
              Salvo que expresamente lo establezcan las leyes aplicables, ningún tercero que no sea parte en este Contrato (con excepción de cualquiera de las Empresas del Grupo Costco) tendrá derecho a hacer cumplir las disposiciones contenidas en los Documentos Contractuales del Sitio.<br>
              <br>
              <strong>23. Subtítulos</strong><br>
              Los subtítulos que son utilizados como encabezados al inicio de cada cláusula se incluyen únicamente para efectos de claridad y para facilitar la lectura. No pretenden describir la totalidad del contenido de una cláusula ni tampoco deben ser considerados para efectos de interpretación de estos Términos y Condiciones. La interpretación de cada cláusula deberá realizarse de acuerdo con su contenido.<br>
              <br>
              <strong>24. Dudas, quejas y reclamaciones</strong><br>
              En caso de dudas, quejas y/o reclamaciones relativas al contenido de los Documentos Contractuales del Sitio, Usted puede ponerse en contacto con nosotros a través de los teléfonos y direcciones que se encuentran disponibles para su consulta en la sección "Contáctenos" de nuestro Sitio Web.<br>
              <br>
              <strong> 25. Legislación aplicable y jurisdicción</strong><br>
              En caso de que Usted se encuentre inconforme con los artículos adquiridos a través del Sitio web por favor póngase en contacto con nosotros a los teléfonos o medios disponibles en la Tienda en Línea. Nosotros haremos todo lo posible por resolver su problema en los siguientes 30 días hábiles contados a partir de la fecha en que Usted nos haga llegar su reclamación.<br>
              <br>
              Para la interpretación y cumplimiento del presente contrato las partes están de acuerdo en someterse a las leyes de los Estados Unidos Mexicanos. Para cualquier desavenencia, las partes podrán acudir a la Procuraduría Federal del Consumidor en su ámbito administrativo para conciliar sus diferencias; de subsistir dichas diferencias, las partes se someten expresamente a los tribunales competentes de la Ciudad de México, Distrito Federal, quienes serán los únicos que podrán conocer de cualquier juicio o reclamación relacionado con las transacciones que se realizan en el Sitio web. Las partes renuncian de manera expresa a cualquier otro fuero presente o futuro que por razón de sus domicilios presentes o futuros pudiera corresponderles.<br>
              &nbsp;
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="p-4 accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#collapse2">
              <b>Política de entrega, devoluciones y cancelaciones</b>
            </button>
          </h2>
          <div id="collapse2" class="accordion-collapse collapse">
            <div class="accordion-body">
              Esta política se aplica a los artículos adquiridos a través de nuestra tienda en línea: Costco.com.mx<br>
                <br>
                <strong> ¿Cobra Costco algún cargo por la entrega de los artículos?</strong><br>
                Sí, el cargo está incluido en el precio del artículo.<br>
                <br>
                <strong>¿Cuáles son las modalidades que utiliza Costco para la entrega de los artículos?</strong><br>
                Entrega de artículos chicos y medianos: La mayoría de los artículos serán entregados por FedEx. Por lo regular, el tiempo de entrega es de 3 días hábiles contados a partir del día en que recibe su confirmación de compra. Los artículos son entregados de lunes a viernes. No se realizan entregas durante días festivos.<br>
                <br>
                Entrega de artículos de gran tamaño: La mayoría de los artículos serán entregados por FedEx. El tiempo de entrega de dichos artículos es de 5 a 12 días hábiles. Por favor considere que los artículos de gran tamaño se entregan a nivel de la calle, sobre la banqueta, a la entrada de la casa o edificio señalado para la entrega. La mensajería no es responsable de llevar los artículos a un piso superior o inferior a menos que se indique en la ficha que establece los "Términos de Entrega" de la página del artículo. Por favor considere que el servicio de entrega no incluye el desempaque ni la instalación, a menos que se indique en los "Términos de Entrega" del artículo. <br>
                <br>
                Antes de realizar un pedido, por favor planifique cómo cargará los artículos al interior de su domicilio. Asimismo, revise si existen condiciones especiales de entrega para el artículo seleccionado. Las condiciones especiales de entrega se publicarán en la ficha de "Términos de Entrega" localizada en la página en la que se muestra el artículo.<br>
                <br>
                Entrega parcial de artículos de un pedido: Los artículos son enviados desde diferentes ubicaciones. Por ello, usted puede recibir artículos amparados por una misma orden en distintas entregas.<br>
                <br>
                Entrega de joyería y diamantes: Costco asegura que usted recibirá el producto adquirido a través de UPS. El tiempo estimado de entrega es de 5 a 10 días hábiles a partir de que su pedido haya sido confirmado. Una vez que el artículo ha sido enviado a UPS usted puede rastrear su pedido ingresando el número de guía de UPS en el sitio web de esta empresa (<a href="http://www.ups.com">www.ups.com</a>). Los plazos de entrega pueden variar en caso de condiciones climáticas adversas y/o trámites aduanales. La entrega requiere forzosamente firma del destinatario.<br>
                <br>
                <strong>¿Cómo puedo conocer el estatus de mi pedido?</strong><br>
                Para conocer el estatus que guarda su orden, ingrese a la sección '"Mi Cuenta" en el sitio Costco.com.mx. En forma paralela, usted puede en todo momento monitorear la localización actual de su pedido haciendo clic en la liga electrónica (link) que le fue proporcionada en el correo electrónico de confirmación de su pedido.<br>
                <br>
                <strong>¿Por qué mi pedido no ha llegado a tiempo?</strong><br>
                Puede ser por varias razones. Por ejemplo, por condiciones climáticas adversas o por la existencia de días festivos, entre las principales causas. Por favor revise periódicamente su cuenta de correo a fin de verificar si le hemos enviado alguna notificación especial explicándole la razón del retraso. También puede ponerse en contacto con nuestro Centro de Atención a Socios para Compras en Línea al teléfono 55 5200 8214.<br>
                <br>
                <strong>¿Qué pasa si mi artículo está dañado?</strong><br>
                Llame a nuestro Centro de Atención a Socios para Compras en Línea al teléfono 55 5200 8214. Nosotros recogeremos el artículo dañado en la dirección de entrega que se nos proporcionó. Asimismo, usted puede devolver el artículo dañado en cualquier momento en nuestras sucursales; nosotros le reembolsaremos totalmente el precio del producto de conformidad con nuestras políticas. Para hacer válida esta garantía, por favor examine detalladamente la mercancía amparada por su pedido antes de firmar de recibido o tan pronto como le sea posible. Si usted se da cuenta que el artículo presenta algún daño, rechace la entrega y no firme de recibido.<br>
                <br>
                <strong>¿Por qué he recibido únicamente parte de mi pedido?</strong><br>
                Aunque usted haya adquirido varios artículos en una misma orden de compra es posible que reciba dichos artículos en entregas por separado. Por favor consulte la sección "Mi Cuenta'" en el sitio web Costco.com.mx para revisar sus órdenes de compra y la forma en que se está desarrollando su entrega.<br>
                <br>
                <strong>¿En qué consiste la garantía de satisfacción al cliente de Costco y la "Política de Entrega, Devoluciones y Cancelaciones"?</strong><br>
                En Costco, aseguramos su satisfacción en cada producto que vendemos mediante una política de reembolso total.<br>
                <br>
                Para obtener un reembolso inmediato de su dinero (incluyendo gastos de envío) la tienda en línea de Costco México le ofrece la posibilidad de devolver la mercancía en cualquiera de las sucursales ubicadas en Territorio Nacional. Por su seguridad, esta disposición no aplica para la devolución y/o reembolso de artículos de joyería.<br>
                <br>
                También podrá devolver cualquier artículo adquirido en nuestra tienda en línea, incluyendo artículos de joyería, u obtener el reemplazo de un artículo defectuoso o que no lo haya satisfecho, contactándonos vía correo electrónico: atencionalsocio@costco.com.mx o llamando a nuestro Centro de Atención a Socios para Compras en Línea de las 8 a.m. a las 7 p.m., de lunes a viernes, excepto días festivos. Al ponerse en contacto con nosotros, se emitirá una autorización de devolución y se procederá al trámite que corresponda. Los reemplazos de mercancías solo procederán si contamos con artículos en existencia.<br>
                <br>
                Los productos que a continuación se señalan, sólo podrán ser devueltos dentro de los 90 (noventa) días siguientes a la fecha de entrega: televisiones, computadoras, tabletas, cámaras, video cámaras, reproductores MP3 y teléfonos celulares.<br>
                <br>
                Para cualquier devolución, el producto deberá encontrarse en las mismas condiciones que al momento de su entrega y estar acompañado de todas sus partes, accesorios, manuales y en su empaque original.<br>
                <br>
                Para ayudarnos a brindarle un servicio más eficiente, cuando usted nos llame para solicitar una devolución o un reemplazo de cualquier producto adquirido en nuestra tienda en línea, por favor tenga a la mano la siguiente información:<br>
                <br>
                <p>1.-Dirección de correo electrónico de la persona que realizó la compra;<br>
                2.-Número de la membresía del Socio que realizó la compra;<br>
                3.-Confirmación de orden de compra y/o número de artículo.</p>
                <br>
                <strong>¿En qué momento debo esperar a recibir mi reembolso?</strong><br>
                a) Devoluciones hechas en la sucursal. Si usted devuelve la mercancía en cualquiera de nuestras sucursales, el reembolso será a la misma forma de pago utilizada para generar la orden de compra sin excepción, apegándonos en todo momento a lo que establece en la materia la Ley Federal para la Prevención e Identificación de Operaciones con Recursos de Procedencia Ilícita.<br>
                <br>
                b) Devoluciones hechas a través de nuestro Centro de Atención a Socios para Compras en Línea. Los reembolsos serán procesados una vez que la mercancía haya sido recibida y verificada. Por favor tome en cuenta que el proceso para verificar la autenticidad de los artículos de joyería puede tomar más tiempo. Cuando el artículo es devuelto por esta vía, el dinero será reembolsado directamente a la tarjeta de crédito del socio que fue utilizada para la transacción.<br>
                <br>
                <strong>¿Qué pasa si tengo dudas sobre mis pedidos en línea o acerca de mi membresía Costco?</strong> Si usted tiene alguna pregunta relacionada con este Sitio web o respecto a su membresía Costco, por favor revise el estado de sus pedidos en la sección "Mi cuenta". Del mismo modo, puede ponerse en contacto con nuestro Centro de Atención a Socios para Compras en Línea al teléfono 55 5200 8214. También puede acudir a nuestras oficinas corporativas ubicadas en Blvd. Magnocentro # 4, San Fernando, La Herradura, Huixquilucan, Edo. De México, o enviarnos un correo electrónico a <a href="mailto:atencionalsocio@costco.com.mx" target="_blank">atencionalsocio@costco.com.mx</a>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="p-4 accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#collapse3">
              <b>Aviso de privacidad</b>
            </button>
          </h2>
          <div id="collapse3" class="accordion-collapse collapse">
            <div class="accordion-body">
                <p>Costco de México, S.A. de C.V. (“Costco” o “Nosotros”), sociedad con domicilio en Av. Magnocentro No. 4, San Fernando, la Herradura, C.P. 52760, Huixquilucan, Estado de México es el responsable del tratamiento de sus datos personales.</p>
                <p><strong>El compromiso de Costco con su privacidad</strong></p>
                <p>En Costco respetamos su derecho a la privacidad y a la protección de sus datos personales. Nosotros no vendemos o rentamos a terceros sus datos. Solamente transferimos o compartimos a terceros sus datos personales en los términos establecidos en este Aviso de Privacidad. Estas comunicaciones se realizan únicamente si usted las ha consentido o bien cuando no se requiere su consentimiento, en términos de la legislación aplicable. Asimismo, para nosotros resulta importante que usted cuente con la capacidad de realizar decisiones bien informadas acerca de la forma en que usamos sus datos personales.</p>
                <p>Este Aviso de Privacidad explica las políticas y prácticas de privacidad que se rigen en Costco con relación al tratamiento que hacemos de sus datos personales (entendiendo por tratamiento la obtención, el uso, la divulgación, y almacenamiento de dichos datos) y las medidas que tomamos para proteger sus datos. Este Aviso está dirigido a: (1) Nuestros clientes, cuando realizan compras en nuestras sucursales en México o; (2) Nuestros clientes, cuando utilizan nuestra página web, localizada en<a href="https://www.costco.com.mx/">www.costco.com.mx</a> (el “Sitio web”).</p>
                <p>Cuando nuestros clientes reciban servicios o productos de nuestros Centros de Ayuda Auditiva, Óptica y Farmacia, se les solicitará revisar un aviso de privacidad (generalmente, un aviso de privacidad simplificado) y se les solicitará que proporcionen su consentimiento por escrito para la obtención y uso de sus datos personales. Estos avisos de privacidad simplificados se encuentran vinculados a este Aviso de Privacidad y dichos datos serán procesados bajo los términos que se establecen en este Aviso de Privacidad.</p>
                <p><strong>1. ¿Qué son los datos personales?</strong></p>
                <p>Se consideran datos personales cualquier información concerniente a una persona física, que la identifique o que pueda ser asociada a una persona identificable.</p>
                <p><strong>2. ¿Qué datos personales son obtenidos por Costco?</strong></p>
                <p>Para los fines establecidos en este Aviso de Privacidad, podemos obtener los datos personales que se refieren a continuación:</p>
                <p>a. Datos de identificación: información que permite diferenciarlo de otros individuos. Estos datos incluyen: nombre, título, firma autógrafa, firma electrónica, registro federal de contribuyentes (RFC); copia del documento con el cual acredita su identidad (Credencial para Votar con Fotografía u otro tipo de documento);</p>
                <p>b. Datos de contacto: información que nos permite mantenernos en contacto con usted. Esos datos incluyen su domicilio, domicilio fiscal, domicilio para efectos de realizar entregas, correo electrónico, teléfono particular u otro teléfono de contacto;</p>
                <p>c. Datos patrimoniales o financieros: información relativa a sus bienes o derechos. Costco puede obtener datos de su tarjeta de crédito para efecto de completar su afiliación o para renovar su membresía; Costco conservará su número de tarjeta, fecha de vencimiento y nombre del titular únicamente si usted lo ha consentido para que dicha información sea utilizada en el proceso de renovación automática de su membresía;</p>
                <p>d. Registros electrónicos: esta información incluye información de compras (en almacenes o en nuestra tienda en línea), dirección IP con la que accede al Sitio web, preferencias de usuario, tipo de navegador; actividad en el sitio, registros de imágenes y/o voz obtenidos a través de sistemas de video-vigilancia en sucursales, entre otros registros.</p>
                <p>Como parte de nuestros servicios, las personas que han obtenido su afiliación a Costco, mediante la firma del correspondiente Contrato de Membresía (los "Socios") pueden proporcionar datos personales referidos anteriormente respecto de su esposa o esposo o cualquier otra persona, para efecto de que Costco pueda registrar a los tarjeta-habientes adicionales. Por favor asegúrese de proporcionarnos sus datos completos y precisos de dichos terceros.</p>
                <p><strong>3. ¿Qué datos personales sensibles son obtenidos por Costco?</strong></p>
                <p>Costco puede obtener ciertos datos personales que son considerados como sensibles en términos de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (la "LFPDPPP"). Costco puede obtener datos relacionados con su salud en nuestros Centros de Ayuda Auditiva, Óptica y Farmacia. Esta información es obtenida cuando usted visita nuestros Centros de Ayuda Auditiva, Óptica y Farmacia en nuestras tiendas. En Costco estamos convencidos de la importancia de proteger la privacidad de su información de salud y, por lo tanto, hemos implementando procedimientos especiales para proteger dichos datos sensibles. Por favor revise los avisos de privacidad simplificados que le serán proporcionados en nuestros Centros de Ayuda Auditiva, Óptica y Farmacia y que forman parte de este Aviso de Privacidad. Los siguientes datos personales podrían ser obtenidos de usted en nuestros Centros de Ayuda Auditiva, Óptica y Farmacia:</p>
                <p>a. Farmacia</p>
                <p>Podremos recabar su nombre, dirección, teléfono, edad, sexo, alergias y otros datos relacionados con sus recetas médicas. Obtenemos esta información para poder surtir sus recetas médicas. Esta información se obtiene en los casos en que nos encontramos obligados por ley a recabar este tipo de información; también puede obtenerse para efecto de identificar posibles riesgos que pudieran originarse por la interacción de medicamentos peligrosos u otros problemas de salud. Utilizamos esta información para procesar su pedido, ponernos en contacto con usted para cualquier pregunta y para proporcionarle el asesoramiento que necesite.</p>
                <p>b. Centros de ayuda Auditiva/Óptica</p>
                <p>Podremos obtener información de su salud (por ejemplo, medicinas que actualmente toma o enfermedades crónicas que padece, etc.). Costco utiliza esta información para practicarle una evaluación auditiva y sugerirle el auxiliar auditivo que resulte más adecuado para usted. Asimismo para que los profesionales de nuestro Centro de Ayuda Auditiva puedan mantenerse en contacto con usted y darle seguimiento a su caso.</p>
                <p>En general, Costco no obtiene datos personales sensibles de usted a través del Sitio web. Cuando Costco obtenga de usted datos personales sensibles, le solicitará, previamente, su consentimiento por escrito.</p>
                <p><strong>4. Obtención de sus datos personales</strong></p>
                <p>Costco obtiene datos de usted ya sea personalmente o de manera directa (v.g. a través de correo electrónico, vía telefónica o a través de su interacción con el Sitio web). Algunos ejemplos son los siguientes:</p>
                <ul>
                    <li>Cuando usted llena una solicitud de afiliación para obtener su membresía de Costco, o para renovar su membresía;</li>
                    <li>Cuando usted se registra para acceder y usar el Sitio web;</li>
                    <li>Cuando usted se registra en el Sitio web para recibir información y promociones;</li>
                    <li>Cuando usted adquiere productos o servicios a través del Sitio o en nuestras tiendas;</li>
                    <li>Cuando se pone en contacto con nosotros, cualquiera que sea el motivo de su comunicación, a través del Sitio web, de alguna de nuestras sucursales, o a través de nuestro Centro de Atención a Socios para Compras en Línea;</li>
                    <li>Cuando usted participa en alguna promoción o encuesta.</li>
                </ul>
                <p>Costco puede obtener de manear automática cierta información cuando usted visita el Sitio web. Esta información incluye la dirección IP asociada a su equipo de cómputo y el sistema operativo que utiliza, la página web desde la cual usted fue enlazado a nuestro Sitio web, su actividad dentro del Sitio web, la fecha y hora en la que visitó nuestra tienda en línea y sus compras. Esta información puede ser obtenida a través del uso de "Cookies" y "Web Beacons". Para mayor información sobre estas tecnologías,<a href="section11">consulte más adelante</a> la sección específica.<br>
                Costco también puede obtener información de usted de manera indirecta cuando ésta nos es proporcionada por terceros a quienes hemos contratado para apoyarnos en procesos específicos. Estos procesos incluyen la corrección de registros, los servicios de prevención de fraude y el ofrecimiento de ofertas o productos especiales. Es posible que conjuntemos la información que recibimos de estos terceros con aquella que ya tenemos de usted.</p>
                <p><strong>5.- Uso de sus datos personales</strong></p>
                <p>En general, los datos personales que obtenemos de usted son utilizados para procesar sus solicitudes y transacciones; para proveerle servicios de alta calidad; para hacerle saber de oportunidades que consideramos que podrían ser de su interés y para administrar su cuenta. Algunas finalidades específicas para las cuales sus datos son procesados son las siguientes:</p>
                <p>a. Para procesar su solicitud y su pago (incluyendo la evaluación de su método de pago, para efectos de prevención de fraude) y llevar a cabo la entrega de su pedido;</p>
                <p>b. Para administrar su cuenta y su membresía. Esta finalidad incluye el procesar sus datos para efectos de facturación; procesar devoluciones de productos; llevar un histórico de sus transacciones; administrar programas de lealtad, descuentos y recompensas; llevar a cabo aclaraciones e investigaciones;</p>
                <p>c. Comunicarnos con usted por diferentes motivos relacionados con su compra incluyendo aspectos relacionados con la entrega de su pedido, notificarle el retiro de productos o aspectos de seguridad;</p>
                <p>d. Informarle sobre posibles oportunidades relacionadas con su membresía y de programas relacionados y;</p>
                <p>e. Para fines de mercadotecnia. Podemos hacerle llegar publicaciones, encuestas, o información promocional de diversos tipos tales como cupones, ofertas (incluyendo ofertas personalizadas) y recomendaciones sobre productos (la "Información Promocional").</p>
                <p>Por favor considere que el hacerle llegar Información Promocional no es una actividad que consideremos esencial para mantener la relación que sostenemos con usted. Si usted prefiere no recibir Información Promocional, Costo le facilita el hacernos saber esta decisión. Para conocer más acerca de los medios que Costco le ofrece para que usted pueda limitar la forma en que Costco usa o divulga sus datos personales, por favor consulte la sección "Opciones para Limitar el Uso o Divulgación de sus Datos Personales" establecida en este Aviso.</p>
                <p>Usted puede contactarnos en cualquier momento para rechazar el recibir Información Promocional. El hecho de que usted decida no recibir Información Promocional no afectará su posibilidad de recibir de nosotros los servicios o productos que usted nos solicite.</p>
                <p><strong>6.- Transferencias de sus datos personales</strong></p>
                Costco puede compartir o transferir sus datos personales en los términos que se describen a continuación.<br>
                <p>a. Empresas que nos prestan servicios. Costco puede remitir sus datos personales a empresas que nos prestan algún servicio. Estos servicios se prestan por instrucciones nuestras, en los términos de los contratos correspondientes. Por ejemplo, Costco puede contratar a un proveedor para que se encargue de prestar diversos servicios relacionados con el comercio electrónico. Estos servicios incluyen el procesamiento de pago a través de tarjetas de crédito, el envío de la mercancía, el envío de los correos electrónicos relacionados, la aplicación de descuentos y el análisis de información; entre otros aspectos. En caso de que alguno de estos proveedores requiera tener acceso a sus datos personales, nosotros exigiremos a dicho proveedor que únicamente utilice sus datos personales en la medida que dicho uso resulte necesario para la ejecución del servicio contratado. Costco solicita a estas empresas mantener de manera confidencial la información que reciben y a regresar dicha información a Costco cuando ya no requieren utilizarla. Por favor considere que en tanto que estos terceros pueden estar localizados fuera de México, estas transferencias pueden implicar una transferencia de sus datos a otro país.</p>
                <p>b. A nuestras afiliadas y a sociedades que pertenecen al Grupo Corporativo de Costco. Costco puede compartir sus datos personales con cualquiera de nuestras afiliadas y/o las empresas que pertenecen a nuestro mismo grupo corporativo. En tanto que nuestras afiliadas se encuentran localizadas fuera de México, por favor considere que sus datos podrían ser transferidos a otros países. Costco se esfuerza por asegurar que las empresas de nuestro grupo que pueden recibir o tener acceso a sus datos personales operen bajo los mismos procesos y políticas internas en materia de privacidad; asimismo, Costco se esfuerza por asegurarse que cada una de sus afiliadas cumpla con las leyes y regulación aplicables a la privacidad y la protección de datos personales en cada jurisdicción.</p>
                <p>c. Socios Titulares. El Socio titular de la membresía se encuentra autorizado para designar o remover a otros titulares de membresías (titulares de membresía complementarias; titulares de membresías adicionales) y a tomar otras decisiones relacionadas con la cuenta; Costco puede mostrar al titular de la membresía datos personales de dichos terceros en lo tocante a las actividades relacionadas con la cuenta. Costco solamente provee esta información al titular de la membresía y únicamente cuando esta información se solicita en nuestros almacenes; todo titular debe presentar su identificación para efectos de tener acceso a la información.</p>
                <p>d. Transferencias a terceros. Le informamos que Costco puede transferir sus datos personales a terceros, en la medida que dicha transferencia resulte necesaria para poder procesar su orden de compra. En este sentido, sus datos pueden ser transferidos a:</p>
                <p><em>1. Empresas que prestan servicios de procesamiento de pagos y prevención de fraude.</em>En caso de que usted pague con su tarjeta de crédito, su número de tarjeta de crédito y la información sobre su compra serán entregados a la empresa que se encarga de procesar los pagos o al emisor de la tarjeta (y a sus prestadores de servicios o afiliadas, quienes participan en los servicios de verificación de fraudes en tarjetas de crédito). La transferencia resulta necesaria para poder procesar su transacción, para poder identificar riesgos de fraude relacionados a su tarjeta y para poder reembolsarle su dinero en su tarjeta de crédito si usted decide cancelar su orden o devolver algún artículo;</p>
                <p><em>2. Empresas de mensajería, logística o fabricantes de productos.</em> Costco puede transferir sus datos personales (incluyendo, nombre, dirección de entrega y datos de contacto) a las empresas de logística, mensajería o a los vendedores de productos que participan en el proceso de entrega de los productos que usted ha adquirido.<br>
                En cualquier caso Costco proporciona a los proveedores y a cualquier otro tercero que participe en alguna actividad relacionada con el proceso de compra o entrega de los bienes, únicamente aquella información que resulta necesaria para efecto de hacerle llegar los productos o servicios que usted ha contratado o adquirido y exigimos a dichos proveedores el mantener dicha información como confidencial y a no utilizarla para ningún fin distinto al referido.<br>
                En tanto que estas empresas, pueden estar localizadas fuera de México, estas transferencias podrían implicar una transferencia internacional de sus datos personales.</p>
                <p>Por favor considere que si usted nos solicita el realizar una transacción en nuestro Sitio o en nuestras tiendas, las transferencias de datos establecidas en esta cláusula 6.c) resultarán precisas para que nosotros podamos procesar su orden y cumplir con la obligaciones que hemos asumido frente a usted. Por ello, si usted no está de acuerdo en que se realicen estas transferencias, le rogamos que no haga uso de nuestro Sitio web.<br>
                Costco no será responsable por los datos personales que usted proporcione directamente a las empresas referidas en la cláusula 6.c); por favor consulte las políticas, prácticas y avisos de privacidad de estas empresas antes de proveerles directamente a ellas sus datos personales.<br>
                <br>
                e. Otros usos o divulgación de sus datos personales. Adicionalmente, Costco puede usar o divulgar sus datos personales cuando consideremos, de buena fe, que la legislación aplicable nos permite usar o divulgar sus datos, en términos de los artículos 4 y 37 de la LFPDPPP. Lo anterior incluye, por ejemplo, cuando dicha transferencia resulte necesaria para protegerlo a usted, para cumplir con algún proceso legal o con requerimientos de autoridades, para responder a reclamaciones o para proteger los derechos de propiedad o la seguridad de Costco, de sus afiliadas, de los empleados de Costco, de los Socios o los derechos de terceros.<br>
                Se hace notar que la información relacionada con nuestros Socios, incluyendo sus datos personales, podrían ser comunicados o transferidos a un tercero, en el contexto de la negociación de una fusión o una venta de activos o una adquisición.</p>
                <p><strong>7. Protección de los datos personales y de información asociada a tarjetas de crédito; medidas de seguridad</strong></p>
                <p>En Costco, hemos establecido medidas de seguridad físicas, administrativas y técnicas para proteger sus datos personales en contra de daño, pérdida, alteración, destrucción o el uso, acceso o tratamiento no autorizado, mientras dichos datos se encuentran bajo nuestro control.</p>
                <p>Hemos establecido ciertos procesos adicionales para proteger los datos personales sensibles que son obtenidos por nuestros Centros de Ayuda Auditiva, Óptica y Farmacia.</p>
                <p>Con relación a la información de las tarjetas de crédito, se nos exige el obtener, procesar y conservar la información de tarjetas que se utilizan para pagos, de conformidad con las reglas de seguridad que han sido adoptadas por las empresas fabricantes de tarjetas de crédito como lo son Visa, MasterCard y American Express. Además, cuando usted nos proporciona sus datos personales en línea, esa información es codificada antes de la transmisión utilizando un protocolo de seguridad llamado SSL (Secure Sockets Layer). También utilizamos SSL para que usted pueda ver en línea, con seguridad, su cuenta y la información de registro.</p>
                <p>A la información de la cuenta en línea sólo se puede acceder mediante el uso de una contraseña. Usted debe mantener su contraseña de forma confidencial. Usted es responsable de todas las operaciones que otra persona haga en el Sitio web, utilizando la contraseña de la que usted es responsable. En caso de que usted crea que su contraseña está siendo mal utilizada, por favor háganoslo saber de inmediato enviando un correo electrónico a<a href="mailto:atencionalsocio@costco.com.mx" target="_blank">atencionalsocio@costco.com.mx</a></p>
                <p><strong>8. Sus derechos "ARCO"</strong></p>
                <p>De conformidad con la LFPDPPP, usted goza de los derechos para acceder, rectificar y cancelar los datos personales que nos ha proporcionado. También cuenta con el derecho de oponerse a ciertas actividades de tratamiento que llevamos a cabo y con el derecho de revocar en cualquier momento el consentimiento que nos haya otorgado para procesar sus datos en la medida que la ley lo permita. Los derechos de Acceso, Rectificación, Cancelación y Oposición antes mencionados, son comúnmente conocidos como "Derechos ARCO". Para el ejercicio de sus Derechos ARCO o de su derecho de revocación, por favor contáctenos a la siguiente dirección de correo electrónico:<a href="mailto:privacidad_datos@costco.com.mx">privacidad_datos@costco.com.mx</a>. También puede realizar esta solicitud en cualquiera de nuestras tiendas acudiendo al área de Membresías.</p>
                <p>Nosotros le comunicaremos, cuando menos: (i) la información que usted deberá proporcionarnos para identificarse y los documentos que necesitará adjuntar a su solicitud; en su caso, la información que su representante legal deberá proporcionar para identificarse y para acreditar que está actuando en su nombre y representación; (ii) los plazos en los que recibirá una respuesta con relación a su solicitud; (iii) información respecto a cómo debe de presentar su solicitud, incluyendo los formularios que puede utilizar (en caso de existir) y; (iv) la modalidad o medio en que le entregaremos la información a usted (que generalmente será mediante la entrega de copias o mensajes de datos).</p>
                <p>Usted podrá actualizar, revisar o corregir la información almacenada en su cuenta directamente, tras acceder a "Mi Cuenta" utilizando la contraseña correspondiente. Usted puede actualizar la información general de su membresía o de su cuenta, directamente en cualquiera de nuestras sucursales, si usted es el titular de la membresía.</p>
                <p><strong>9. Dudas o quejas</strong></p>
                <p>Si usted tiene alguna pregunta o desea contactarnos por alguna razón, incluyendo para formular una queja, usted puede realizar cualquiera de los siguientes procedimientos:</p>
                <ul>
                    <li>Visítenos en el Área de Membresías en cualquiera de nuestras sucursales en México</li>
                    <li>Comuníquese con nosotros al 01 800 801 11 11</li>
                    <li>Envíenos un correo a<a href="mailto:privacidad_datos@costco.com.mx">privacidad_datos@costco.com.mx</a></li>
                </ul>
                <p>&nbsp;</p>
                <p><strong>10. Opciones para limitar el uso o divulgación de sus datos personales</strong></p>
                <p>Costco le ofrece la posibilidad de tomar decisiones sobre cómo usamos sus datos personales y le ofrecemos diversos medios para informarnos acerca de su decisión. Por favor note que sus derechos de manifestar su negativa para un tratamiento, previo al tratamiento, no podrán ser ejercitados por su esposa o por los titulares de membresías adicionales o complementarias. Sin embargo, cuando usted registra a otras personas como socios de membresía complementaria o socios de membresía secundaria o adicional en nuestras tiendas, nuestro personal le ofrecerá la opción de rechazar el recibir Información Promocional; esta opción también podrá ser ejercitada por usted en favor de los otros titulares.</p>
                <p>Si usted no desea recibir Información Promocional, incluyendo nuestros correos electrónicos, usted: (a) recibirá la opción de rechazar recibir esta información tanto en el Sitio web como al registrarse en nuestras sucursales; (b) solicitar su cancelación a las listas haciendo clic en la palabra "eliminar" que aparece como un hipervínculo en cualquiera de los correos electrónicos; (c) puede visitar cualquiera de nuestras sucursales y hacer su solicitud en el área de Membresías; (d) puede llamarnos a nuestro Centro de Atención a Socios para Compras en Línea al teléfono 01 800 801 11 11; o (e) puede enviarnos un correo a<a href="mailto:privacidad_datos@costco.com.mx">privacidad_datos@costco.com.mx</a></p>
                <p><strong>11. Aspectos específicos de privacidad en nuestro sitio web</strong></p>
                <ul>
                  <li><u>Cookies</u></li>
                </ul>
                <p>En nuestro Sitio web utilizamos "Cookies". Las cookies son pequeños archivos de datos que se almacenan en el disco duro de su equipo de cómputo o del dispositivo de comunicación electrónica que usted utiliza cuando navega en nuestro Sitio. Estos archivos de datos permiten intercambiar información de estado entre nuestro Sitio web y el navegador que usted utiliza. La "información de estado" puede revelar medios de identificación de sesión, medios de autenticación o sus preferencias como usuario, así como cualquier otro dato almacenado por el navegador respecto del Sitio web.</p>
                <p>Las cookies nos permiten monitorear el comportamiento de un usuario en línea. Utilizamos la información que es obtenida a través de cookies para ayudarnos a optimizar su experiencia de compra. A través del uso de cookies podemos, por ejemplo, personalizar en su favor nuestra página de inicio de manera que nuestras pantallas se desplieguen de mejor manera de acuerdo a su tipo de navegador. Las cookies también nos permiten ofrecerle recomendaciones personalizadas respecto de productos, y correos electrónicos.</p>
                <p>Las cookies no son software espía, y Costco no recopila datos de múltiples sitios o comparte con terceros la información que obtenemos a través de cookies.</p>
                <p>Como la mayoría de los sitios web, nuestros servidores registran su dirección IP, la dirección URL desde la que accedió a nuestro Sitio web, el tipo de navegador, y la fecha y hora de sus compras y otras actividades. Utilizamos esta información para la administración del sistema, solución de problemas técnicos, investigación de fraudes y para nuestras comunicaciones con usted.</p>
                <p>Por último, le informamos que el Sitio web utiliza web beacons. Los web beacons también nos permiten monitorear su comportamiento en medios electrónicos Utilizamos web beacons para determinar cuándo y cuántas veces una página ha sido vista. Utilizamos esta información para fines de mercadotecnia, pero únicamente para nuestras propias prácticas de mercadotecnia.</p>
                <p>Su navegador aceptará las cookies y permitirá la recolección automática de información a menos que usted cambie la configuración predeterminada del navegador. La mayoría de navegadores web permiten que usted pueda gestionar sus preferencias de cookies.</p>
                <p>Puede ajustar su navegador para que rechace o elimine cookies. Los siguientes links muestran como ajustar la configuración del navegador de los navegadores que son utilizados con más frecuencia:</p>
                <p><a href="https://support.google.com/chrome/bin/answer.py?hl=es&amp;answer=95647">Chrome</a><br>
                  <a href="https://support.apple.com/kb/index?page=search&amp;fac=all&amp;q=cookies%20safari">Safari</a><br>
                  <a href="https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we">Firefox</a><br>
                  <a href="https://support.microsoft.com/en-us/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09">Microsoft Edge</a><br>
                  <a href="https://support.microsoft.com/en-us/windows/delete-and-manage-cookies-168dab11-0753-043d-7c16-ede5947fc64d">Internet Explorer</a></p>
                <p>Si se inhabilitan las cookies del Sitio web, nuestro Sitio no se cargará apropiadamente.</p>
                <li><u>Enlaces a otros sitios</u></li>
                
                <p>Desde nuestro Sitio web, usted puede enlazarse a sitios web de terceros. Estos terceros están autorizados para ofrecer productos y/o servicios a nuestros Socios o bien, prestan funciones y servicios en nuestro Sitio web, como información de productos y críticas sobre productos. Cuando por el contexto específico no resulte claro que usted está siendo dirigido a un sitio web de un tercero, nos esforzamos para notificarle que está visitando un sitio en el que se aplica un aviso de privacidad diferente. En general, por favor considere que cualquier información personal que usted entrega en las páginas a las que usted accede a través de hipervínculos es obtenida directamente por los terceros que administran dichos sitios y el tratamiento de dicha información se encuentra sujeto a las políticas de privacidad de ese tercero. Nosotros no somos responsables por el contenido ni por las prácticas de privacidad y seguridad ni por los términos y condiciones que sean de aplicación en los sitios web a los cuales es posible enlazarse electrónicamente. Le recomendamos leer y entender los avisos de privacidad y los términos aplicables antes de proporcionar sus datos personales en esos sitios.</p>
                <p><strong>12. Uso del sitio realizado por menores de edad</strong></p>
                <p>Recomendamos a los padres de familia el asumir un papel pro activo en el uso que sus hijos hacen del Internet. No es nuestra intención el recopilar información de niños y, en general, de menores de 18 años de edad. Si eres menor de 18 años, no debes proporcionar información al Sitio Web.</p>
                <p>Queda prohibido a los menores de 18 años el surtir o resurtir una receta médica en nuestro Sitio web.</p>
                <p><strong>13. Modificaciones al aviso de privacidad</strong></p>
                <p>Costco se reserva el derecho de modificar este Aviso de Privacidad en cualquier momento. Sin embargo, nosotros le informaremos el hecho de que se han realizado modificaciones al Aviso, haciendo patente en la parte superior del Aviso la fecha en que fue actualizado por última vez. El Aviso actualizado será publicado en nuestro Sitio Web. Le sugerimos revise nuestro Aviso de Privacidad para asegurarse de que comprende cómo serán utilizados sus datos personales. Toda modificación a nuestro Aviso de Privacidad estará vigente a los 30 días naturales contados a partir de su publicación.</p>
                <p>En caso de que realicemos una modificación relevante a este Aviso, pondremos a su disposición nuevamente el Aviso de Privacidad en los términos establecidos por la ley. Estos cambios incluyen entre otros: un cambio en: nuestra identidad; las finalidades que dieron origen o son necesarias para la relación entre usted y nosotros; la incorporación de nuevas finalidades que requieran su consentimiento; la obtención de datos personales sensibles, patrimoniales adicionales o financieros a aquellos previamente informados y las demás casos que establece la regulación aplicable.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <jsp:include page="footer.jsp"/>
</body>
</html>